### ISSUE TITLE
Error on composer network ping --card 

### ISSUE THREAD

**Issue by kpbird** [hyperledger/composer#3944] opened 2018-05-01 10:19 UTC
I have created business network using hyperledger composer and deployed on hyperledger fabric. 

## Context
**Step 1: install network**

Ketan-Parmar:fabric-dev-servers ketan$ composer network install --card PeerAdmin@hlfv1 --archiveFile ~/Downloads/hardware-assets.bna 
✔ Installing business network. This may take a minute...
Successfully installed business network hardware-assets, version 0.0.4-deploy.0

Command succeeded

**Step 2: start network**

Ketan-Parmar:fabric-dev-servers ketan$ composer network start --networkName hardware-assets --networkVersion 0.0.4-deploy.0 --networkAdmin admin --networkAdminEnrollSecret adminpw --card PeerAdmin@hlfv1 --file networkadmin.card
Starting business network hardware-assets at version 0.0.4-deploy.0

Processing these Network Admins: 
	userName: admin

✔ Starting business network definition. This may take a minute...
Successfully created business network card:
	Filename: networkadmin.card

Command succeeded

**Step 3: import admin card **
Ketan-Parmar:fabric-dev-servers ketan$ composer card import --file networkadmin.card 

Successfully imported business network card
	Card file: networkadmin.card
	Card name: admin@hardware-assets

Command succeeded

**Step 4: list cards **
Ketan-Parmar:fabric-dev-servers ketan$ composer card list
The following Business Network Cards are available:

Connection Profile: hlfv1
┌───────────────────────┬───────────┬──────────────────┐
│ Card Name             │ UserId    │ Business Network │
├───────────────────────┼───────────┼──────────────────┤
│ admin@hardware-assets │ admin     │ hardware-assets  │
├───────────────────────┼───────────┼──────────────────┤
│ PeerAdmin@hlfv1       │ PeerAdmin │                  │
└───────────────────────┴───────────┴──────────────────┘

Command succeeded

**Step 5: ping network **
Ketan-Parmar:fabric-dev-servers ketan$ composer network ping --card admin@hardware-assets

Writing Node.js report to file: node-report.20180501.154055.21549.001.txt
Node.js report completed
/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:666
				throw error;
				^

Error: Connection is not in the READY state
    at ChannelEventHub._checkConnection (/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:664:17)
    at ChannelEventHub.registerChaincodeEvent (/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:825:8)
    at HLFConnection._registerForChaincodeEvents (/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:279:44)
    at HLFConnection._checkCCListener (/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:256:22)
    at Timeout.ccListenerHandle.setTimeout [as _onTimeout] (/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:381:35)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
Ketan-Parmar:fabric-dev-servers ketan$ composer network ping --card admin@hardware-assets

Writing Node.js report to file: node-report.20180501.154240.21561.001.txt
Node.js report completed
/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:666
				throw error;
				^

Error: Connection is not in the READY state
    at ChannelEventHub._checkConnection (/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:664:17)
    at ChannelEventHub.registerChaincodeEvent (/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:825:8)
    at HLFConnection._registerForChaincodeEvents (/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:279:44)
    at HLFConnection._checkCCListener (/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:256:22)
    at Timeout.ccListenerHandle.setTimeout [as _onTimeout] (/Users/ketan/.nvm/versions/node/v8.10.0/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:381:35)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
Ketan-Parmar:fabric-dev-servers ketan$ composer network ping --card admin@hardware-assets

## Expected Behavior
ping should success

## Actual Behavior
Error while ping

2018-05-01T10:12:40.286Z [193c8120] ERROR    :Composer                 :Invoke()                  Error: The current identity, with the name 'admin' and the identifier '01899e04161a3a6d64670504fa122e55818295352929b6a616333a3739fde3f2', must be activated (ACTIVATION_REQUIRED)

## Your Environment
* Version used: v0.19.3
* Environment name and version (e.g. Chrome 39, node.js 5.4): node v8.10.0
* Operating System and version (desktop or mobile): OSX 10.13.4 (17E199)

The grpc problem also causes the following error to occur:

```
/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/EventHub.js:308
			if(self._stream) state = self._stream.call.channel_.getConnectivityState();
			                                                    ^

TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/EventHub.js:308:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-cli/node_modules/grpc/src/client_interceptors.js:1302:19)
    at InterceptingListener.recvMessageWithContext (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-cli/node_modules/grpc/src/client_interceptors.js:629:19)
    at /home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/composer-cli/node_modules/grpc/src/client_interceptors.js:728:14
```

**Comment by su-ywi** [comment] 2018-05-01 10:32
I got similar errors from 0.19.2
```
> composer network ping -c admin@example.com

Writing Node.js report to file: node-report.20180501.193052.21127.001.txt
Node.js report completed
/home/su-ywi/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:666
                                throw error;
                                ^

Error: Connection is not in the READY state
    at ChannelEventHub._checkConnection (/home/su-ywi/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:664:17)
    at ChannelEventHub.registerChaincodeEvent (/home/su-ywi/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:825:8)
    at HLFConnection._registerForChaincodeEvents (/home/su-ywi/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:279:44)
    at HLFConnection._checkCCListener (/home/su-ywi/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:256:22)
    at Timeout.ccListenerHandle.setTimeout [as _onTimeout] (/home/su-ywi/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:381:35)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

```
but, somehow I can do `composer network ping` with the composer which is installed by yarn
```
> npx composer network ping -c admin@example.com
        Business network version: 0.0.1
        Composer runtime version: 0.19.2
        participant: org.hyperledger.composer.system.NetworkAdmin#admin
        identity: org.hyperledger.composer.system.Identity#6588b81e637a44a5fc2034bdf08338db462635cc4a321a699c1a3dfb29192e7d

Command succeeded
```

**Comment by rohitkhatri** [comment] 2018-05-01 12:31
Getting the same issue

```
Writing Node.js report to file: node-report.20180501.122718.25794.001.txt
Node.js report completed
/home/ubuntu/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:666
				throw error;
				^

Error: Connection is not in the READY state
    at ChannelEventHub._checkConnection (/home/ubuntu/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:664:17)
    at ChannelEventHub.registerChaincodeEvent (/home/ubuntu/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:825:8)
    at HLFConnection._registerForChaincodeEvents (/home/ubuntu/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:279:44)
    at HLFConnection._checkCCListener (/home/ubuntu/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:256:22)
    at EventRegistration.ccEvent.handle.eventHub.registerChaincodeEvent [as onError] (/home/ubuntu/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:290:26)
    at /home/ubuntu/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:572:30
    at Set.forEach (<anonymous>)
    at cc_closer (/home/ubuntu/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:569:12)
    at Array.forEach (<anonymous>)
    at ChannelEventHub._closeAllCallbacks (/home/ubuntu/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/fabric-client/lib/ChannelEventHub.js:578:43)
```

Composer CLI Version: 0.19.3 also tried 0.19.2

**Comment by mbwhite** [comment] 2018-05-01 15:01
Initial investigations have indicated that this is caused by a new version of the GRPC library; this moved to 1.11.0 14 hours ago... backing this off to 1.10.1 appears to work correctly. 

Will lock this down in the composer package.json and raise a JIRA on the fabric-client (that brings in this GRPC dependency)

**Comment by mbwhite** [comment] 2018-05-01 15:09
Fixed by #3946

**Comment by mbwhite** [comment] 2018-05-02 08:28
@marckaraujo I believe the following should allow you to get 0.18.1 working.  I'll start from the point of any empty npm module. 
```
npm init -y
npm install --save-dev grpc@1.10.1
npm install --save composer-cli@0.18.1 composer-client@0.18.1 composer-rest-server@0.18.1
```

This will install grpc at the working level, then the composer modules at 0.18.1
Note that the CLI and REST server are installed locally. 
You can then use `npx composer --version` for example.

n

**Closed** 2018-05-04 10:01 UTC
Labels: P1, bug

**Comment by AmaalK** [comment] 2018-05-04 21:48
@mbwhite I tried using your commands, however, I need sudo access, and when I do it using sudo, I still get access error. Any suggested advice?

**Comment by AmaalK** [comment] 2018-05-04 22:34
@mbwhite I tried out your commands, and they ran successfully, however, during the ./createPeerAdminCard.sh step, I had the error "No version of composer-cli has been detected, you need to install composer-cli at v0.19 or higher" , so should I install everything in the latest version then uninstall the composer-cli and install the older version?

**Comment by gauravc95** [comment] 2018-05-05 09:04
similar errors on 0.19.4, anyone can help me how to solve it so I can deploy network.

**Comment by gauravc95** [comment] 2018-05-05 10:10
@marckaraujo i tried running the cmds(u mention above) but still getting the same error!

**Comment by marckaraujo** [comment] 2018-05-05 19:53
@gauravc95 Do a `npm install --save grpc@1.10.1` inside the composer-rest-server and composer-cli module

**Comment by qraccess** [comment] 2018-05-06 05:41
I have tried `npm install --save grpc@1.10.1` inside the composer-reset-server nad composer-cli, but still got the same error.

**Comment by qraccess** [comment] 2018-05-06 07:11
Anyone can deploy business network on the latest(0.19.4) successfully? 
I have tried uninstalled `npm uninstall -g composer-cli composer-rest-server generator-hyperledger-composer`, Then installed them again. 
I also tried `npm install --save grpc@1.10.1` inside the composer-cli,composer-rest-server,composer-playground module. same error still occurred.

> error: [Hyperledger-Composer] :HLFConnectionManager     :fabric-client()                                                                                                                        [ChannelEventHub.js]: _checkConnection - connection is not in the ready state                                                                                                             . state: UNKNOWN_STATE
warn: [Hyperledger-Composer] :HLFConnection            :_registerForChaincodeEve                                                                                                             n Eventhub for CC Events disconnected with error Connection is not in the READY                                                                                                              state
warn: [Hyperledger-Composer] :HLFConnection            :_checkCCListener()                                                                                                                     could not find any connected event hubs out of 1 defined hubs to listen on for                                                                                                              chaincode events
/usr/local/lib/node_modules/composer-playground/node_modules/_fabric-client@1.1.                                                                                                             0@fabric-client/lib/ChannelEventHub.js:666
                                throw error;
                                ^
Error: Connection is not in the READY state
    at ChannelEventHub._checkConnection (/usr/local/lib/node_modules/composer-pl                                                                                                             ayground/node_modules/_fabric-client@1.1.0@fabric-client/lib/ChannelEventHub.js:                                                                                                             664:17)
    at ChannelEventHub.registerChaincodeEvent (/usr/local/lib/node_modules/compo                                                                                                             ser-playground/node_modules/_fabric-client@1.1.0@fabric-client/lib/ChannelEventH                                                                                                             ub.js:825:8)
    at HLFConnection._registerForChaincodeEvents (/usr/local/lib/node_modules/co                                                                                                             mposer-playground/node_modules/_composer-connector-hlfv1@0.19.4@composer-connect                                                                                                             or-hlfv1/lib/hlfconnection.js:279:44)
    at HLFConnection._checkCCListener (/usr/local/lib/node_modules/composer-play                                                                                                             ground/node_modules/_composer-connector-hlfv1@0.19.4@composer-connector-hlfv1/li                                                                                                             b/hlfconnection.js:256:22)
    at Timeout.ccListenerHandle.setTimeout [as _onTimeout] (/usr/local/lib/node_                                                                                                             modules/composer-playground/node_modules/_composer-connector-hlfv1@0.19.4@compos                                                                                                             er-connector-hlfv1/lib/hlfconnection.js:381:35)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

**Comment by vsharma030** [comment] 2018-05-07 21:17
I am also facing the issue related to the above error. I have raised the issue on stackoverflow, [https://stackoverflow.com/questions/50219592/error-connection-is-not-in-the-ready-state-at-channeleventhub-checkconnection](url).

**Comment by krishna81m** [comment] 2018-08-07 23:35
@odrodrig reproduced error in composer v0.19.12
https://github.com/hyperledger/composer/issues/4303

```
composer network ping -c admin@basic-sample-network
Error: Error trying to ping. Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier '01899e04161a3a6d64670504fa122e55818295352929b6a616333a3739fde3f2', must be activated (ACTIVATION_REQUIRED)
Command failed
```

**Comment by krishna81m** [comment] 2018-08-08 06:24
Also, @mbwhite  apparently, following your composer 0.18.1 installation steps:

npm init -y
npm install --save-dev grpc@1.10.1
npm install --save composer-cli@0.18.1 composer-client@0.18.1 composer-rest-server@0.18.1

When I run a create peer admin, it fails asking for 0.19 again!!

./createPeerAdminCard.sh
Development only script for Hyperledger Fabric control
Running 'createPeerAdminCard.sh'
FABRIC_VERSION is unset, assuming hlfv11
FABRIC_START_TIMEOUT is unset, assuming 15 (seconds)

No version of composer-cli has been detected, you need to install composer-cli at v0.19 or higher

**Comment by krishna81m** [comment] 2018-08-08 06:51
Ok, finally found a solution to the composer-cli "ACTIVATION" problem:
https://github.com/hyperledger/composer/issues/4303#issuecomment-411304780
