### ISSUE TITLE
Intro/tutorial/quickstart links from README are broken

### ISSUE THREAD

**Issue by l2fprod** [hyperledger/composer#1455] opened 2017-07-04 08:39 UTC
These links are not found:

![image](https://user-images.githubusercontent.com/12746550/27822161-050c4858-60a5-11e7-94bd-5f37ac4d21bf.png)

**Comment by Tobias-Hunter** [comment] 2017-07-05 08:00
Closing as duplicate of #1410

**Closed by Tobias-Hunter** 2017-07-05 08:00 UTC
Labels: bug, docs
