### ISSUE TITLE
As a user of Composer I can add/define ACL files through the editor

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#684] opened 2017-04-13 10:56 UTC
Currently via fabric composer it is possible to add/define new model (cto) and script file (js) but not an ACL file.

## Context
If I import a new Business Network, which does not have an ACL file, it is not possible to define one in the composer. We already have the ability to edit an existing ACL file (with inbuilt validation) but not define an empty one.

## Expected Behavior
When using the "+ Add File" button, an ACL file option is present

## Actual Behavior
User can only add cto or js file

## Possible Fix
Support ACL file addition

**Comment by sstone1** [comment] 2017-05-09 07:49
Duplicate of #505.

**Closed by sstone1** 2017-05-09 07:49 UTC
Labels: enhancement, user story
