### ISSUE TITLE
Conditions in Query  won't return right results from second parameter

### ISSUE THREAD

**Issue by RoberVH** [hyperledger/composer#3667] opened 2018-03-22 15:50 UTC
Composer v0.16.3
composer-rest-server v0.16.3

Model
asset Aircraft identified by aircraftId {
  o String      aircraftId 

  o Ownership   ownershipType default="LEASED"

  // Number of seats per class 
  o Integer     firstClassSeats      range = [4,]
  o Integer     businessClassSeats   range = [6, 20]
  o Integer     economyClassSeats    range = [30, ]

  o String      nickName  optional 
}

enum Ownership {
  o   LEASED
  o   OWNED
}

Query

query AllAircraftsbySeatsCounts {
  description: "Returns all Aircrafts in the registry"
  statement:  
    SELECT  org.acme.airline.aircraft.Aircraft
    WHERE(firstClassSeats >= _$firstC_lowlLimit AND businessClassSeats >= _$busissnes__lowlLimit AND economyClassSeats >= _$economy__lowlLimit)
	
	
When running through Rest Server API, the condition in the middle of the WHERE clause is ignored, the other two are respected and return right results. Changing the order of the conditions will result in the middle one failing to be recognized.

**Comment by sstone1** [comment] 2018-03-26 06:56
Duplicate of #3460.

**Closed by sstone1** 2018-03-26 06:56 UTC
Labels: duplicate
