### ISSUE TITLE
Use of caret for node.js package dependency versions

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1740] opened 2017-08-03 10:26 UTC
According to SemVer primer
```
Given a version number MAJOR.MINOR.PATCH, increment the:
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
```
Prefixing a single semver version string with the ~ character defines a range of acceptable versions that include all patch versions from the one specified up to, but not including, the next minor version. "~1.2.3" can be approximately expanded as ">=1.2.3 <1.3.0".
Prefixing a single semver version string with the ^ character defines a range of acceptable versions that include all patch and minor versions from the ones specified up to, but not including, the next version. So "^1.2.3" can be approximately expanded as ">=1.2.3 <2.0.0"

The discussion is about whether we should be using caret instead of tilde as the number of times we get broken due to a dependent package minor version change is becoming disruptive.

But one of the problems could be that packages only include bug fixes at a minor level (rather than a micro level) or only provide bug fixes for the current minor level rather than previously released minor levels.

This is not a recommendation but I think it is something we should discuss as we have started fixing versions of our dependencies when dependency breaks occur.

**Comment by sstone1** [comment] 2017-08-17 20:53
Let's not have multiple issues for "we need to better manage our dependencies".
Closing as a duplicate of #651.

**Closed by sstone1** 2017-08-17 20:53 UTC
Labels: duplicate
