### ISSUE TITLE
A Bulk Loader

### ISSUE THREAD

**Issue by adrianblakey** [hyperledger/composer#2004] opened 2017-08-25 05:21 UTC
I have a need to load say 3m+ objects into a ledger. This probably should be a Fabric capability and not a Composer capability, however if it's purely a Fabric capability there should be some Composer support to map a Composer model definition onto either an existing Asset or Participant ledger or both.

## Context
Do I need to say more? I obviously need to see what's available in Fabric - more research needed...

## Expected Behavior
If composer explicitly maintains a mapping then maybe the task is to document that file and where to place it. If it's not explicit what's needed is some mapping syntax in a "model mapping" file - that could be run through a code generator to create code usable by composer.

**Comment by sstone1** [comment] 2017-08-28 17:30
Duplicate of:
As a user I would like to bulk load assets and participants #769

**Closed by sstone1** 2017-08-28 17:30 UTC
Labels: duplicate
