### ISSUE TITLE
REST and mongodb error

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1794] opened 2017-08-08 14:06 UTC
```
{
  "error": {
    "statusCode": 500,
    "name": "Error",
    "message": "Error trying login and get user Context. TypeError: Cannot read property '_key' of null",
    "stack": "Error: Error trying login and get user Context. TypeError: Cannot read property '_key' of null\n    at client.getUserContext.then.then.catch (/Users/Caroline/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:292:34)"
  }
}
```

Step to recreate

1. Set rest server up using github passport and mongodb

2. start rest server : `composer-rest-server -p hlfv1 -n org-acme-biznet -i admin -s adminpw -N required -S true -w true`

3. Add an identity to the wallet

4. check you can create a participant

5. Stop and restart the rest server

6 check you still have the identity in the wallet

7. Try and create a participant

That will then give the error at the top

**Comment by CR4YU** [comment] 2017-08-28 07:53
Please fix this bug as fast as possible. I cannot continue my very important project.

**Comment by wiejskichlop** [comment] 2017-08-28 08:20
In our case:
1. authorize using LDAP, mongo
2. add participant
3. issue an identity to that participant
4. add to wallet
5. set as default in the existing (default) wallet. Ping, etc. works nicely.
6. authorize as another LDAP user
7. authroize back as the first user
8. ping returns : `{
  "error": {
    "statusCode": 500,
    "name": "Error",
    "message": "Error trying login and get user Context. TypeError: Cannot read property '_key' of null",
    "stack": "Error: Error trying login and get user Context. TypeError: Cannot read property '_key' of null\n    at client.getUserContext.then.then.catch (/Users/Caroline/.nvm/versions/node/v6.9.5/lib/node_modules/composer-rest-server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:292:34)"
  }
}`

**Comment by sstone1** [comment] 2017-08-28 17:40
@CR4YU @wiejskichlop can you confirm which version of the REST server you are using? You can check using `composer-rest-server -v`. This bug should be fixed in v0.11.3.

**Comment by wiejskichlop** [comment] 2017-08-29 06:51
@sstone1 we were using v0.11.2. After the update everything works as intended. Thanks!

**Closed** 2017-08-29 06:59 UTC
Labels: bug, P2, rest

**Comment by PRRemon** [comment] 2017-09-24 02:47
@wiejskichlop Hi How did you set up LDAP Authentication using passport? Can you please guide me?

**Comment by wiejskichlop** [comment] 2017-09-26 13:15
@PRRemon Well, it's basically following this tutorial: https://hyperledger.github.io/composer/integrating/enabling-rest-authentication.html

With a few exceptions:
1) You have to do
` npm install -g passport-ldapauth`

2) You should have a LDAP server somewhere, obviously. You can create one on the same machine

3) example COMPOSER_PROVIDERS config:

```
COMPOSER_PROVIDERS = {
"ldap":{  
      "provider":"ldap",
      "authScheme":"ldap",
      "module":"passport-ldapauth",
      "authPath":"/auth/ldap",
      "successRedirect":"/",
      "failureRedirect":"/",
      "server":{  
         "url":"ldap://localhost:389",
         "bindOn":"cn=admin,dc=test, dc=com",
         "bindCredentials":"admin",
         "searchBase":"ou=users,dc=test,dc=com",
         "searchFilter":"(uid={{username}})"
      }
   }
}

**Comment by PRRemon** [comment] 2017-10-09 03:21
@wiejskichlop I tried the same way. But when I hit the URL localhost:3000/auth/ldap it gives 404 error.

**Comment by PRRemon** [comment] 2017-10-09 03:56
@wiejskichlop I resolved the error. Thanks for the info.

**Comment by DennisM330** [comment] 2017-10-13 19:57
What was the resolution of the error for the 404 error on  localhost:3000/auth/ldap. Seeing the same error

**Comment by mallikarjunasai995** [comment] 2019-02-23 05:48
> @wiejskichlop I resolved the error. Thanks for the info.

what was the resolution am also getting the same error ...
