### ISSUE TITLE
Deploy a blockchain business network to the cloud

### ISSUE THREAD

**Issue by parismollo** [hyperledger/composer#4358] opened 2018-08-28 14:00 UTC
Having multiple errors to deploy an API on IBM cloud.

## Context
The tutorial (https://www.ibm.com/developerworks/cloud/library/cl-deploy-blockchain-starter-plan-network/index.html) explains how to deploy a business network API on the IBM cloud. However, I'm facing some issues and due to my lack of experience on the subject, multiple questions appear.

I'm not using the provided samples from ibm, I'm using my own business network definition 

Im using my own docker  image that i created by following the composer tutorial : https://hyperledger.github.io/composer/latest/integrating/deploying-the-rest-server

## Steps
tutorial: https://www.ibm.com/developerworks/cloud/library/cl-deploy-blockchain-starter-plan-network/index.html

## Expected Behavior
After running : 
$ cf login -a https://api.ng.bluemix.net --sso
$ cf push car-auction --docker-image ibmblockchain/composer-rest-server:0.19.5 \
    -c "composer-rest-server -c admin@carauction-network -n never -w true" \
    -i 1 -m 256M --no-start --no-manifest
$ cf set-env car-auction NODE_CONFIG "${NODE_CONFIG}"
$ cf start car-auction

the output should me something like this:

`Starting app car-auction in org Sanjay-Bluemix / space dev as ...
Creating container
....
Successfully destroyed container
 
0 of 1 instances running, 1 starting
...
1 of 1 instances running
0 of 1 instances running, 1 starting
...
1 of 1 instances running
 
App started
 
OK
 
App car-auction was started using this command `composer-rest-server -c admin@carauction-network -n never -w true`
 
Showing health and status for app car-auction in org Sanjay-Bluemix / space dev as ...
OK
 
requested state: started
instances: 1/1
usage: 256M x 1 instances
urls: car-auction.mybluemix.net
last uploaded: Mon May 21 16:12:14 UTC 2018
stack: cflinuxfs2
buildpack: unknown
 
     state     since                    cpu     memory           disk         details
#0   running   2018-05-21 09:19:39 AM   16.8%   154.9M of 256M   1.3M of 1G`
## Actual Behavior
Multiple Errors like .....

`2018-08-28T15:23:58.00+0200 [APP/PROC/WEB/0] ERR Error: Cannot initialize connector undefined: Unable to load requested module @ampretia/composer-wallet-cloudant
`
or 
`2018-08-28T15:20:24.25+0200 [APP/PROC/WEB/0] ERR { Error: Card not found: admin@xxxx
`

the admin card not found error appears on both cases 
## Context & Questions
1. The docker image for a specific network should be the one I created by following the tutorial : https://hyperledger.github.io/composer/latest/integrating/deploying-the-rest-server or should be the one provided in the tutorial ibmblockchain/composer-rest-server ?? considering that I using my own business network.

2. When I make composer-card-list the card admin@xxxx appears normally but It's says on the log that can't find the exaclty same card....

ps: Composer card list is super unstable, in the exactly same directory i was having different outputs when running composer card list, and no changes were made at all.

**Comment by davidkel** [comment] 2018-08-28 15:07
Sorry but this is a duplicate of https://stackoverflow.com/questions/52007097/deploying-composer-rest-server-api-on-ibm-cloud-card-not-found-port 

and Github is for new enhancement requests and bugs only, so closing.

**Closed by davidkel** 2018-08-28 15:07 UTC
