### ISSUE TITLE
Chaincode instantiation and ACL handling

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#927] opened 2017-05-10 14:20 UTC
(Not sure if this has been covered by another issue so please ref and close if so)
Chaincode instantiation comprises of bring up the composer runtime and installing the business network archive through the chaincode init function.

As part of that bring up acl checking is done and unless the identity returned is null from the getIdentity call, the instantiate will fail due to acl check rejection.

The chaincode is currently hardcoded to return null if any user who is instantiating the chaincode contains the text admin in the common name of the certificate used to create the proposal which is not good. 

HLF V1 I believe (Still need to test once alpha2 drop is available) define the following
- install must be done by a peer admin
- instantiate can be done by any MSP member (which should include a peer admin of course)

Also there has been discussion around the fact that you only need to instantiate on a single peer in a channel (ie no need to send instantiate to all peers). Organisations may only have to perform an install on their own peers meaning we need an install only option.

**Comment by sstone1** [comment] 2017-05-11 07:27
Duplicate of #670.

**Closed by sstone1** 2017-05-11 07:27 UTC
Labels: hlfv1, P1
