### ISSUE TITLE
[Master] "Error: Invalid continuation byte" using Mandarin as value in an asset.

### ISSUE THREAD

**Issue by David-Kim-TPE** [hyperledger/composer#4508] opened 2018-11-05 06:54 UTC
Put Mandarin in the value of an asset, a certain combination of characters can cause "Error: Invalid continuation byte"
## Context

If my blockchain application can't handle certain input, It stops me from using the application. The blockchain technology should be able to take in UTF-8 characters as it is a fundemental requirement.

## Expected Behavior

When I create an asset, I should be able to put Japenese, Korean, Mandarin, and all the UTF-8 encoding characters in the value field of a key and complete my transaction of creating the asset.
## Actual Behavior

When I put a certain string "桃稅法1063702754" in the field of an asset. An error occurs and I can't complete the transaction of creating the asset.
## Possible Fix

Maybe some encoding can be adopted before saving the asset value and a decoding will be necessary for reading the asset. 
## Steps to Reproduce

1. Create a network https://github.com/David-Kim-TPE/archive-network
2. Try to create an asset "OfficialDocument" with Issue_No being "桃稅法1063702754"
https://github.com/David-Kim-TPE/archive-network/blob/master/asset002
3. See if the transaction can be successful.

## Context

I want to be able to use Mandarin in my fabric framework without the chance of being denied by encoding issues.

## Your Environment

* Version used: archive-network 0.0.8
* Environment name and version: Composer runtime version 0.20.3
* Operating System and version: Ubuntu 16.04 64 (desktop)
* Link to your project: https://github.com/David-Kim-TPE/archive-network

**Comment by mahoney1** [comment] 2018-11-15 13:00
Not sure where you're trying this. Strings support UTF8 yes, and it works for me having just tried it out.  I just tried your issue in Playground - my sample code has this simple model/function on an asset update:

```
asset LandTitle identified by id {
  o String id
  o Boolean forSale default=false
  o String name
  o String lastName
}

async function UnlockLandTitle(tx) {
const landTitleRegistry = await getAssetRegistry(NS + ".LandTitle");

  if (tx.landTitle.forSale) {
    throw new Error(
      `Land Title with id ${tx.landTitle.getIdentifier()} is already unlocked for sale`
    );
  }

  // Unlock asset to be for sale 
  tx.landTitle.forSale = true;
  tx.landTitle.name = "美青";
  tx.landTitle.lastName = "桃稅法1063702754";

  await landTitleRegistry.update(tx.landTitle); 
}
```

Updated asset shows:
```

{
  "$class": "org.landreg.LandTitle",
  "id": "1",
  "area": 10,
  "forSale": true,
  "name": "美青",
  "lastName": "桃稅法1063702754"
}
```

**Comment by mahoney1** [comment] 2018-11-16 17:35
@David-Kim-TPE  - please raise a separate issue, to investigate whether this error is something that comes from fabric-node-sdk or fabric-shim and will be assigned to @davidkel . Thanks.

**Comment by davidkel** [comment] 2018-11-19 20:18
@David-Kim-TPE don't worry about raising a separate issue. I will try to recreate using the information provided here.

**Comment by davidkel** [comment] 2018-11-21 13:49
Ok, confirmed this is a bug in the fabric-shim, not composer but will need to get a fix from fabric published before it can be included in composer.

**Comment by davidkel** [comment] 2018-11-21 15:35
https://jira.hyperledger.org/browse/FAB-12961

**Comment by davidkel** [comment] 2018-12-05 08:53
I don't know if there is a plan to release any more fabric-shims for 1.1,1.2,1.3. The fix has gone into fabric 1.4, but as composer is not picking up 1.3 or 1.4 shims unless fabric publish a 1.1, 1.2 shim for composer 0.19, 0.20 to pick up then we can't get this fix into composer.

**Comment by davidkel** [comment] 2018-12-07 10:04
@David-Kim-TPE I know this will be in the 1.4 version of fabric-shim so will be available with fabric 1.4 is released. It may be that fabric will release new npm modules for previous releases of fabric-shim but I am not aware of any plans to do so yet.

**Comment by David-Kim-TPE** [comment] 2018-12-10 06:07
@davidkel, thank you so much!

**Closed** 2019-01-07 14:42 UTC
Labels: bug, hlfv1, prereq

**Comment by mahoney1** [comment] 2019-01-10 12:49
@David-Kim-TPE Composer 0.20.6 has been released today FYI https://github.com/hyperledger/composer/releases
