### ISSUE TITLE
Apply filter on array value in REST API to get particular data

### ISSUE THREAD

**Issue by MonarthS** [hyperledger/composer#4278] opened 2018-07-26 11:36 UTC
I want to apply some filter on array, here is my data:

```
{
    "$class": "bc.blockchain.user",
    "userId": "IND_1532580568687",
    "netobj": [
      "Find Jobs,Find Assigments",
      "visible",
      "draft"
    ],
    "firstName": [
      "Donald",
      "visible",
      "draft"
    ],
    "lastName": [
      "duck",
      "visible",
      "draft"
    ],
    "Gender": [
      "Male",
      "visible",
      "draft"
    ],
    "submittedOn": "Jul 26, 2018, 10:22 AM"
  }
```
Now, If I want to get data where `"firstName"` array contains value `"Donald"`.

So, how can I do that ?

I am applying filter `{"where":{"firstName":{"contains":["Donald"]}}}` on REST API `http://localhost:3000/api/bc.blockchain.user`.

But it shows error that **`"Property firstName of type String[] cannot be compared with a literal value. "`**

**Comment by davidkel** [comment] 2018-09-16 18:47
As documented here
https://hyperledger.github.io/composer/latest/business-network/query
contains is not a supported filter
you probably want to use a predefined query instead.
Closing as not a bug.

**Closed by davidkel** 2018-09-16 18:47 UTC

**Comment by LaljiG** [comment] 2018-11-05 15:56
Hi David
I'm very knew to Hyperledger Composer/Blockchain Networks and Loopback etc..
I have managed to use the composer RESTApi from a client app and was also looking for functionality  (e.g. support for like or contains operator t use with the where filter) that monarthS was after. Before going down predefined queries do you know if there is likely to be support for additional operators in future or is exclusion deliberate by design and forever?
Thanks 
LaljiG
