### ISSUE TITLE
gyp ERR! EACCES during 'composer network start'

### ISSUE THREAD

**Issue by b509** [hyperledger/composer#3870] opened 2018-04-19 08:43 UTC
When running `composer network start` after successfully creating a BNC for the admin, importing it and running `composer network install` I get the error log seen below.

## Context
Setup of the underlying, distributed Fabric network (using VMs for 1 orderer, 1 peer, 1 kafka, none yet for a CA) through [this tutorial](https://blockchain-fabric.blogspot.de/2017/09/underconstruction-setting-up-blockchain.html), crypto material was copied to the respective VMS manually.

Then installation of Composer on peer as described in [this tutorial](https://hyperledger.github.io/composer/latest/tutorials/deploy-to-fabric-multi-org). Yes, this is the Multi-Org Tutorial, because later the plan is to setup a second peer and let it join too.
Problems arise at step seventeen with the full command:
`composer network start -c PeerAdmin@sampl -n sampl -A admin -S adminpw -V 1.0.0
`

Communication between the peer/orderer/kafka works fine because I was able to create and join a channel.

## Expected Behavior
Successful start of the network

## Actual Behavior
No docker containers are present before or after, when executing `docker ps`.
The following error appears (full log with `export $DEBUG=composer:*`, copied from the file created in ~/.composer/logs). The first error starting with `undefined:ModelManager` seems to print the whole code, I replaced that by [...] for better readability.

> 2018-04-19T07:49:07.317Z INFO    undefined:ModelManager             :addSystemModels()         [...]
2018-04-19T07:49:07.861Z INFO    undefined:LoadModule               :loadModule()              Loading composer-wallet-filesystem from /home/user/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/composer-wallet-filesystem {}$
2018-04-19T07:49:07.939Z INFO    undefined:ConnectionProfileManager :getConnectionManagerByTyp Looking up a connection manager for type {"0":"hlfv1"}$
2018-04-19T07:49:08.945Z INFO    undefined:ConnectionProfileManager :getConnectionManagerByTyp Using this connection manager  {"0":{"connectionProfileManager":{}}}$
2018-04-19T07:49:44.080Z ERROR   undefined:HLFConnectionManager     :fabric-client()           [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm WARN deprecated fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

> x509@0.3.3 install /chaincode/output/node_modules/x509
> node-gyp rebuild

> gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.13.0-38-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /chaincode/output/node_modules/x509
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN sampl@1.0.0 No repository field.
npm WARN The package composer-common is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

> npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! x509@0.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the x509@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-19T07_49_42_459Z-debug.log
"
    at new createStatusError (/home/user/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:64:15)
    at /home/user/.nvm/versions/node/v8.11.1/lib/node_modules/composer-cli/node_modules/grpc/src/client.js:585:15 {}$

`sudo journalctl -fu docker.service` gives the following output

> -- Logs begin at Wed 2018-04-11 16:17:50 CEST. --
Apr 19 09:49:09 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T09:49:09.909765456+02:00" level=warning msg="Your kernel does not support swap limit capabilities,or the cgroup is not mounted. Memory limited without swap."
Apr 19 09:49:10 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T09:49:10+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/386b72b4aa27deea479dffd31dd02694cf8438ad01b9422040091ff19842a540/shim.sock" debug=false module="containerd/tasks" pid=29165
Apr 19 09:49:42 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T09:49:42+02:00" level=info msg="shim reaped" id=386b72b4aa27deea479dffd31dd02694cf8438ad01b9422040091ff19842a540 module="containerd/tasks"
Apr 19 09:49:42 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T09:49:42.690465597+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Apr 19 09:49:44 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T09:49:44.159635707+02:00" level=warning msg="could not write error response: write unix /var/run/docker.sock->@: write: broken pipe"
Apr 19 09:51:26 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T09:51:26.793110050+02:00" level=warning msg="Your kernel does not support swap limit capabilities,or the cgroup is not mounted. Memory limited without swap."
Apr 19 09:51:27 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T09:51:27+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/2f5a6132ba24eae5c06bf3cc88b9ad3c378740160efc1e0a906b178b75ad6721/shim.sock" debug=false module="containerd/tasks" pid=29416
Apr 19 09:51:54 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T09:51:54+02:00" level=info msg="shim reaped" id=2f5a6132ba24eae5c06bf3cc88b9ad3c378740160efc1e0a906b178b75ad6721 module="containerd/tasks"
Apr 19 09:51:54 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T09:51:54.433086011+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Apr 19 09:51:56 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T09:51:56.240710578+02:00" level=warning msg="could not write error response: write unix /var/run/docker.sock->@: write: broken pipe"

## Existing issues

- Various issues related to the `gpy ERR! EACCES: permission denied`: 
[1](https://github.com/angular/angular-cli/issues/6848), [2](https://github.com/node-serialport/node-serialport/issues/1499)), probably irrelevant because I seem to not be installing inside my own file-system, but in the docker-container's one.

- Issues related to the last docker error `Apr 19 09:51:56 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T09:51:56.240710578+02:00" level=warning msg="could not write error response: write unix /var/run/docker.sock->@: write: broken pipe"`, probably the issue, since there is also an npm warning `npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0`
[1](https://github.com/docker-php/docker-php/issues/195)
[2](https://github.com/moby/moby/issues/22221) (they seemed to solve it with downgrading Docker)
[3](https://github.com/hyperledger/composer/issues/1670) seems relevant, unfortunately adding the environment variables for `CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE, CORE_VM_DOCKER_ATTACHSTDOUT, CORE_LOGGING_PEER, CORE_CHAINCODE_LOGGING_LEVEL, CORE_VM_ENDPOINT` changes nothing

## Your Environment
Ubuntu 16.04 (`uname -a`  -->  Linux sampl-hyper-dev2 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
`docker -v`  -->  Docker version 18.03.0-ce, build 0520e24
`docker-compose -v` - ->  docker-compose version 1.13.0, build 1719ceb
`npm -v`  -->  5.8.0
`node -v`  -->  v8.11.1
`composer --version`  -->  v0.19.0

**Comment by b509** [comment] 2018-04-19 09:54
When checking Docker's status I get the following outputs:

`sudo /etc/init.d/docker status` prints

> docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-04-11 16:17:59 CEST; 1 weeks 0 days ago
     Docs: https://docs.docker.com
 Main PID: 983 (dockerd)
    Tasks: 22
   Memory: 152.9M
      CPU: 40min 35.356s
   CGroup: /system.slice/docker.service
           ├─ 983 /usr/bin/dockerd -H fd://
           └─1157 docker-containerd --config /var/run/docker/containerd/containerd.toml

> Apr 19 11:08:40 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T11:08:40.858974948+02:00" level=warning msg="Your kernel does not support swap limit capabilities,or...out swap."
> Apr 19 11:08:41 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T11:08:41+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/... pid=29993
> Apr 19 11:09:08 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T11:09:08+02:00" level=info msg="shim reaped" id=5ab35dda6d72c6767b66803048be3046bcc7c3ea953b7b362fa5...erd/tasks"
> Apr 19 11:09:08 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T11:09:08.847115386+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=...askDelete"
> Apr 19 11:09:10 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T11:09:10.581032277+02:00" level=warning msg="could not write error response: write unix /var/run/doc...oken pipe"
> Apr 19 11:33:52 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T11:33:52.786470329+02:00" level=warning msg="Your kernel does not support swap limit capabilities,or...out swap."
> Apr 19 11:33:53 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T11:33:53+02:00" level=info msg="shim docker-containerd-shim started" address="/containerd-shim/moby/... pid=30461
> Apr 19 11:34:21 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T11:34:21+02:00" level=info msg="shim reaped" id=7b8704eef18cad083e58e8f0adc52bf25bb485ce890b1813da01...erd/tasks"
> Apr 19 11:34:21 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T11:34:21.913027168+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=...askDelete"
> Apr 19 11:34:23 sampl-hyper-dev2 dockerd[983]: time="2018-04-19T11:34:23.275608801+02:00" level=warning msg="could not write error response: write unix /var/run/doc...oken pipe"
> Hint: Some lines were ellipsized, use -l to show in full.

but` sudo status docker` prints

> status: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

However the latter issue seems to be related to status rather than docker

**Comment by davidkel** [comment] 2018-04-19 10:13
@b509 what environment are you running you ubuntu image on ? Bare Metal, Virtual Machine, VirtualB
ox, VMWare, Hyper-V, Cloud VM, Azure, AWS etc ?

**Comment by davidkel** [comment] 2018-04-19 10:30
@b509 no idea, just curious as I have heard of this problem once before, but have never seen it happen either locally or in our builds so was looking for possible differences.

**Comment by b509** [comment] 2018-04-19 10:35
These seem relevant too:
http://container-solutions.com/running-docker-in-jenkins-in-docker/ (Answer 15)
https://bugzilla.redhat.com/show_bug.cgi?id=1331003 (Comment 15 seems to have found the issue)
https://github.com/buildkite/elastic-ci-stack-for-aws/issues/236 (last comment on 9th of Feb. 17 references a docker-issue that was supposedly fixed in Docker 1.12.6.)

**Comment by b509** [comment] 2018-04-19 10:37
Hm, ok. Wouldyou agree that the central problem seems to be the docker socket problem and not the gyp permission problem?

**Comment by davidkel** [comment] 2018-04-19 10:45
@b509 not sure really as I have never seen it myself. It seems odd to get a file system permission error and the cause would be a docker socket problem but I guess anythings possible

**Comment by b509** [comment] 2018-04-20 06:56
@davidkel Thank you for investing the time. I work only frequently on this project, so it may be some time before I fix this. However, if I find a cause, i'll be sure to tell everyone about it here.

**Comment by davidkel** [comment] 2018-04-20 07:09
@b509 that would be great if you could find out the cause and provide info on it, many thanks

**Comment by sstone1** [comment] 2018-04-20 09:38
Closing - you can still comment with the cause when issue is closed.

**Closed by sstone1** 2018-04-20 09:38 UTC

**Comment by b509** [comment] 2018-05-09 11:38
@davidkel I set the logging to DEBUG and had another look at the peer's logs and found the following:

> [about 700 lines that look alright]
> 
> [grpc] Printf -> DEBU 264[0m grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 192.168.1.123:7051: getsockopt: connection refused"; Reconnecting to {peer1:7051 <nil>}
> 
> [another 300 lines]
> 
> [chaincode] launch -> DEBU 37e[0m start container: sampl:1.0.0(networkid:dev,peerid:other-peer1)
> [chaincode] launch -> DEBU 37f[0m start container with args: /bin/sh -c cd /usr/local/src; npm start -- --peer.address peer1:7052
> [chaincode] launch -> DEBU 380[0m start container with env:
> 	CORE_CHAINCODE_ID_NAME=sampl:1.0.0
> 	CORE_PEER_TLS_ENABLED=false
> 	CORE_CHAINCODE_LOGGING_LEVEL=info
> 	CORE_CHAINCODE_LOGGING_SHIM=warning
> 	CORE_CHAINCODE_LOGGING_FORMAT=%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}
> [container] lockContainer -> DEBU 381[0m waiting for container(dev-other-peer1-sampl-1.0.0) lock
> [container] lockContainer -> DEBU 382[0m got container (dev-other-peer1-sampl-1.0.0) lock
> [dockercontroller] Start -> DEBU 383[0m Cleanup container dev-other-peer1-sampl-1.0.0
> [dockercontroller] stopInternal -> DEBU 384[0m Stop container dev-other-peer1-sampl-1.0.0(No such container: dev-other-peer1-sampl-1.0.0)
> [dockercontroller] stopInternal -> DEBU 385[0m Kill container dev-other-peer1-sampl-1.0.0 (No such container: dev-other-peer1-sampl-1.0.0)
> [dockercontroller] stopInternal -> DEBU 386[0m Remove container dev-other-peer1-sampl-1.0.0 (No such container: dev-other-peer1-sampl-1.0.0)
> [dockercontroller] Start -> DEBU 387[0m Start container dev-other-peer1-sampl-1.0.0
> [dockercontroller] getDockerHostConfig -> DEBU 388[0m docker container hostconfig NetworkMode: host
> [dockercontroller] createContainer -> DEBU 389[0m Create container: dev-other-peer1-sampl-1.0.0
> [dockercontroller] Start -> DEBU 38a[0m start-could not find image <dev-other-peer1-sampl-1.0.0-06046357d3a684226ae366c2300b80f8376e88d113d54b44efc19f221f50c164> (container id <dev-other-peer1-sampl-1.0.0>), because of <no such image>...attempt to recreate image
> [chaincode-platform] generateDockerfile -> DEBU 38b[0m 
> FROM hyperledger/fabric-baseimage:x86_64-0.4.6
> ADD binpackage.tar /usr/local/src
> LABEL org.hyperledger.fabric.chaincode.id.name="sampl" \
>       org.hyperledger.fabric.chaincode.id.version="1.0.0" \
>       org.hyperledger.fabric.chaincode.type="NODE" \
>       org.hyperledger.fabric.version="1.1.0" \
>       org.hyperledger.fabric.base.version="0.4.6"
> ENV CORE_CHAINCODE_BUILDLEVEL=1.1.0
> [util] DockerBuild -> DEBU 38c[0m Attempting build with image hyperledger/fabric-ccenv:x86_64-1.1.0
> [chaincode-platform] func1 -> ERRO 38d[0m Failed to generate platform-specific docker build
> 
> [... as seen above]

Can you read anything from it that might help me? Am I correct in reading it as: The docker build never succeeded before, therefore he has no image. Since he has no image, he tries to build it and while building it gets the node-gyp error? 

Also another things that is odd: If I set '--peer-chaincodedev=true' during peer startup, the 'composer network start' fails much faster and with the following error

> Response from attempted peer comms was an error: Error: 2 UNKNOWN: failed to init chaincode: handler not found for chaincode sampl:1.0.0

That seems intersting. Did I forget an environment variable or something similar? The peer's logs are similar to the above:

> [ccprovider] NewCCContext -> DEBU 3df[0m NewCCCC (chain=ch1,chaincode=sampl,version=1.0.0,txid=0eb3b8212bfa9f23b7362c9cf0fe71cec9b22ff383c244dbd3f6b565ef167f29,syscc=false,proposal=0xc42223aff0,canname=sampl:1.0.0
> [chaincode] sendReady -> DEBU 3e0[0m handler not found for chaincode sampl:1.0.0
> 
> [later]
> 
> failed to init chaincode
> [container] lockContainer -> DEBU 3e2[0m waiting for container(dev-other-peer1-sampl-1.0.0) lock
> [container] lockContainer -> DEBU 3e3[0m got container (dev-other-peer1-sampl-1.0.0) lock
> [dockercontroller] stopInternal -> DEBU 3e4[0m Stop container dev-other-peer1-sampl-1.0.0(No such container: dev-other-peer1-sampl-1.0.0)
> [dockercontroller] stopInternal -> DEBU 3e5[0m Kill container dev-other-peer1-sampl-1.0.0 (No such container: dev-other-peer1-sampl-1.0.0)
> [dockercontroller] stopInternal -> DEBU 3e6[0m Remove container dev-other-peer1-sampl-1.0.0 (No such container: dev-other-peer1-sampl-1.0.0)
> [container] unlockContainer -> DEBU 3e7[0m container lock deleted(dev-other-peer1-sampl-1.0.0)
> [chaincode] Launch -> DEBU 3e8[0m sending init completed
> [chaincode] Launch -> DEBU 3e9[0m LaunchChaincode complete
> [endorser] callChaincode -> DEBU 3ea[0m [ch1][0eb3b821] Exit
> [endorser] simulateProposal -> ERRO 3eb[0m [ch1][0eb3b821] failed to invoke chaincode name:"lscc" , error: handler not found for chaincode sampl:1.0.0

I removed the timestamps for better readability.

**Comment by b509** [comment] 2018-07-11 14:54
For anybody that finds this issue: I was not able to resolve it. Instead of running the fabric-network natively, I used the docker-containers (although distributed on different machines) and it worked.
