### ISSUE TITLE
Starting REST API server on Multiple independent nodes

### ISSUE THREAD

**Issue by rs2015** [hyperledger/composer#3778] opened 2018-04-07 14:23 UTC
My current setup includes following :

Fabric version : 1.1.0
Composer version : 0.18.2

VM 1 - lifelink1 - First machine running “fabric-samples/first-network” byfn.sh - two organization setup - E2E successfully completed. Up and running with two REST API servers on different ports - 3000 and 3001.

VM 2 - hospital1 - 2nd machine was setup using same “fabric-samples/first-network” with custom eyfn.sh script - E2E successfully completed and joined network running on VM 1.

On VM 2 - I run following commands before starting REST API servers

composer card create -p hospital1/byfn-network-hospital1.json -u chloe -n $network -c chloe/admin-pub.pem -k chloe/admin-priv.pem

composer card create -p hospital1/byfn-network-hospital1.json -u chloe -n lifelink-network -c chloe/admin-pub.pem -k chloe/admin-priv.pem

composer card import -f chloe@lifelink-network.card

composer network ping -c chloe@lifelink-network

root@2c0f50fdb6f0:/var/www/app/current/credentials# composer network ping -c chloe@lifelink-network
Error: Error trying to ping. Error: 2 UNKNOWN: error executing chaincode: transaction returned with failure: Error: The current identity, with the name 'admin' and the identifier 'ea173e6aa087cc9b0bfe433ed2f01c8ff939ac100a2b6d67b57cf3fe750cb83c', has not been registered
Command failed

And “composer network ping” command is failing. I know for sure without success on this step, REST API server will not work.

I am not finding any documentation anywhere on how-to successfully do this.

Please see the attached log files generated for each machine using custom developed script.

Thank you
[hospital1-fabric-deployer-log.txt](https://github.com/hyperledger/composer/files/1886427/hospital1-fabric-deployer-log.txt)
[lifelink1-fabric-deployer-log.txt](https://github.com/hyperledger/composer/files/1886430/lifelink1-fabric-deployer-log.txt)

**Comment by sundarsuman** [comment] 2018-06-13 05:54
Hi @rs2015,
Facing the same issue. Have you figured this out yet. Would be a great help.

Thanks

**Comment by AsterixMechant** [comment] 2018-07-02 17:48
I'm having the exact same problem. Except that I can run it smoothly from two computers, but not from a specific new computer. Already checked that I have the correct version of NodeJS and composer packages installed. I'm not running my network on fabric though, but on IBM Blockchain.

**Comment by LeeJCherry** [comment] 2018-07-13 11:06
Did anyone ever resolve this?  Have the same issue

**Comment by ktiwary2** [comment] 2018-07-19 18:36
Ok so I was able to fix this issue. So can you tell me what was were the exact series of steps that you took and what you're trying to do with those commands?
I think this error happens when you've replaced the admin card that is running. Are you trying to upgrade the network?

**Comment by davidkel** [comment] 2018-09-16 18:37
Whenever you get an error such as `The current identity, with the name 'admin' and the identifier 'ea173e6aa087cc9b0bfe433ed2f01c8ff939ac100a2b6d67b57cf3fe750cb83c', has not been registered`. It means you have either 
- used an identity that hasn't been bound to a participant or 
- you have imported a card file in 2 places but that card file contained a use once only secret.
Remember the name of an identity is NOT a unique identifier. Its just the common name field in the certificate and you can have multiple certificates with the same name but they are not the same identity or certificate.
This question is asked a lot and it will always be one of the above to issues and not a bug in composer. There are lots of other explanations on stackover such as
https://stackoverflow.com/questions/51800878/hyperledger-composer-the-current-identity-with-the-name-admin-and-the-ident
Closing as not a bug or enhancement

**Closed by davidkel** 2018-09-16 18:37 UTC
Labels: user error
