### ISSUE TITLE
REST unhelpful example json when submitting a transaction

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1786] opened 2017-08-08 09:10 UTC
When submitting a transaction through the REST explorer using the basic sample network this is the example json

```
{
  "$class": "org.acme.sample.SampleTransaction",
  "asset": "string",
  "newValue": "string",
  "transactionId": "string",
  "timestamp": "2017-08-08T08:31:11.063Z"
}
```

Transaction id and timestamp fields aren't needed and could be confusing for a new user

**Comment by mahoney1** [comment] 2017-08-08 10:13
I believe these were covered by Loopback issues initially here https://github.com/strongloop/loopback/issues/3447 and then re-opened here -> https://github.com/strongloop/loopback/issues/3510

As for timestamp - is there a hideGenerationTimestamp=true  setting or similar?

**Comment by sstone1** [comment] 2017-08-17 22:00
Duplicate of:
Example data for transactions in rest server include {"transactionId": "string"} #663

**Closed by sstone1** 2017-08-17 22:00 UTC
Labels: bug, duplicate, rest

**Comment by himanimukne** [comment] 2018-06-01 04:42
please provide a solution for this, the problem still persists.
even after writing
"transactionId" : false,

this is the error

{
"error": {
"statusCode": 400,
"name": "SyntaxError",
"message": "Unexpected token t in JSON at position 110",
"body": "{\n "$class": "test.AccountTransfer",\n "from": "HimaniAccount",\n "to": "AstatineAccount",\n "amount": 20,\n transactionId: false,\n "timestamp": "2018-06-01T04:33:39.539Z"\n}",
"status": 400,
"stack": "SyntaxError: Unexpected token t in JSON at position 110\n at JSON.parse ()\n at parse (/home/himani/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/body-parser/lib/types/json.js:88:17)\n at /home/himani/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/body-parser/lib/read.js:116:18\n at invokeCallback (/home/himani/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/raw-body/index.js:262:16)\n at done (/home/himani/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/raw-body/index.js:251:7)\n at IncomingMessage.onEnd (/home/himani/.nvm/versions/node/v8.11.2/lib/node_modules/composer-rest-server/node_modules/raw-body/index.js:307:7)\n at emitNone (events.js:106:13)\n at IncomingMessage.emit (events.js:208:7)\n at endReadableNT (_stream_readable.js:1064:12)\n at _combinedTickCallback (internal/process/next_tick.js:138:11)\n at process._tickCallback (internal/process/next_tick.js:180:9)"
}
}


it is not rectified with true either. error 422

**Comment by mahoney1** [comment] 2018-06-01 13:52
hello @himanimukne - I provided a resolution for your external freecodecamp tutorial issue  [here](https://stackoverflow.com/questions/50618081/error-executing-hyperledger-fabric-code-on-localhost3000-through-rest-trans) - please refer.

**Comment by indolia143** [comment] 2018-08-17 16:52
@himanimukne - I also faced that kind of problem, after looking into it and spending lot of time. I found this is not the problem of **npm** and **node.js**, if we are installing them as non root. This is the problem of Loopback so you have to make an api json request without **"transactionId"** and **"timestamp"** means remove both of them.  It will work fine as loopback swagger will update it automatically.
