### ISSUE TITLE
command composer-rest-server with Bus error (core dumped)

### ISSUE THREAD

**Issue by Ryan-fai** [hyperledger/composer#4363] opened 2018-08-31 05:08 UTC
## Context

Follow 'Step Five: Generating a REST server' in tutorial https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial, after run command composer-rest-server and input parms as below:
? Enter the name of the business network card to use: admin@tutorial-network
? Specify if you want namespaces in the generated REST API: never use namespaces
? Specify if you want to use an API key to secure the REST API: No
? Specify if you want to enable authentication for the REST API using Passport: No
? Specify if you want to enable event publication over WebSockets: Yes
? Specify if you want to enable TLS security for the REST API: No

Output from terminal:
Discovering types from business network definition ...
Bus error (core dumped)

## Expected Behavior
sth like http://localhost:3000/explorer should be displayed.

## Actual Behavior
Discovering types from business network definition ...
Bus error (core dumped)

## Steps to Reproduce
Follow 'Step Five: Generating a REST server' in tutorial https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial, after run command composer-rest-server and input parms as below:
? Enter the name of the business network card to use: admin@tutorial-network
? Specify if you want namespaces in the generated REST API: never use namespaces
? Specify if you want to use an API key to secure the REST API: No
? Specify if you want to enable authentication for the REST API using Passport: No
? Specify if you want to enable event publication over WebSockets: Yes
? Specify if you want to enable TLS security for the REST API: No

## Your Environment

* Version used: v0.20.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): 6.4.0
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by liyupi** [comment] 2018-09-19 05:28
I met the same problem and I hope someone can solve it.

**Comment by Dearkano** [comment] 2018-11-21 15:56
Met the problem too, is there any solution?

**Comment by davidkel** [comment] 2018-12-01 11:32
Closing as this is not a bug in composer but either environmental issue such as not enough memory or platform trying to be run on, or perhaps an installation failure.
Check that you are running on the correct pre-reqs, specifically make sure you are running the latest version of Node 8 and not any other Node version (eg 6, 10, 11 etc). That you have at least 4Gb of memory.

**Closed by davidkel** 2018-12-01 11:32 UTC
Labels: user error
