### ISSUE TITLE
Automatically generated identifiers don't take validators into account

### ISSUE THREAD

**Issue by pastadin** [hyperledger/composer#1012] opened 2017-05-17 07:15 UTC
I have the following participant:

```
participant Collector identified by email {
  o String email regex=/[a-z0-9.-]+@[a-z0-9.]+/
  o String firstname
  o String surname
}
```
As you can see, there is a regex validator to ensure the email field is structured as an email should be. However when I go to Test -> Create New Participant I get the following error:

```
Error: Invalid validator for field org.acme.model.Collector#email:8424 org.acme.model.Collector.email: Value + 'email:8424' failed to match validation regex: /[a-z0-9.-]+@[a-z0-9.]+/
```

The error is relatively obvious - the auto generated field is simply `field name` + `number`, while this is fine otherwise it isn't useful here as it violates the validation rule. As a result the JSON structure that normally appears in the dialogue window is not present and as such I cannot edit it to provide a properly formed email identifier:

<img width="730" alt="screen shot 2017-05-17 at 08 13 00" src="https://cloud.githubusercontent.com/assets/9092152/26142489/ab18fe96-3ad8-11e7-98c2-02dbbf9955ac.png">

Would it be possible to request a fix whereby either identifiers are not automatically generated or that if they are, they adhere to validation fields like the others do?

EDIT: I have since discovered this applies to the other attributes as well (not just identifiers), comment is otherwise the same.

Reproduction:

1. Open Up Playground
2. Start an empty project
3. Create a new Model file
4. Paste in the code above
5. Create a new Collector participant

System:

macOS 10.11.6
Chrome 57
composer-playground:latest (0.7.2)

**Comment by dselman** [comment] 2017-05-22 20:08
I don't think it is possible for the data generator to take into account the validators (general case). We should improve the generator however to be tolerant of generating instances that are invalid with respect to the validators, and then let the user fix the generated data.

**Comment by bestbeforetoday** [comment] 2017-06-29 09:45
#1396 effectively describes the same issue, so closing that one as a duplicate of this.

**Comment by samjsmith** [comment] 2017-07-10 11:25
I spoke to @dselman about this and unfortunately, I don't think that it is easily fixed. 

As Dan says it would be nigh on impossible for a generator to generate data that conforms to an arbitrary regex that's enforced by a validator.

It's easy to detect the situation and easy to cause the generator to generate a known value that could be ignored by the validator.  For example this code could be added into the `assignFieldDefaults` function here: https://github.com/hyperledger/composer/blob/master/packages/composer-common/lib/model/typed.js#L151


```                
if (field.getType() === 'String') {
   if(field.validator!==null) {
        if(field.validator.regex) {
            defaultValue = 'AUTO-GEN-DATA-NEEDS-REGEX-VALIDATION';
        }
    }
}
```

Then this line in the StringValidator class could be made aware of this by changing this line: https://github.com/hyperledger/composer/blob/master/packages/composer-common/lib/introspect/stringvalidator.js#L55
to become
`if((value !== null) && (value !== 'AUTO-GEN-DATA-NEEDS-REGEX-VALIDATION')) {`

Then you can get the Playground UI to generate a modal that looks like this: 
![image](https://user-images.githubusercontent.com/16335033/28015897-049762bc-656a-11e7-970c-a835f980e718.png)

However, now the validator is hacked around this, users can then create "valid" instances without changing the generated data e.g. 
![image](https://user-images.githubusercontent.com/16335033/28015955-4213cb6c-656a-11e7-864d-ab248231fda5.png)

Maybe we could consider another validator option of 'Playground' which is used in combination with the special `AUTO-GEN-DATA-NEEDS-REGEX-VALIDATION` to determine whether the check is made? If not then I don't see a way around this one I'm afraid.  

Perhaps the Triage team could look again at this?

**Comment by markcastle3** [comment] 2017-10-06 08:09
@samjsmith @sstone1 do you think we will be able to resolve this one ?

**Comment by mbwhite** [comment] 2017-10-06 08:30
This has some connection with the problem of creating test data for recursive structures. 
Generating test data does rapidly become a complex problem as noted. 

From a user's perspective as well we've already seen confusion being created that some of the data that is created doesn't match the assets they have already created. 

Would be a good side project for a contributor to look into.

**Comment by samjsmith** [comment] 2017-10-09 10:42
Actually the first  problem here, which I hadn't noticed before, is that it's the identifier of the Participant which is required to be restricted by the regex.  This means that the playground can't even provide a basic JSON structure for the user to go and amend. 
I'll do a bit more investigation to see if we could come up with a solution for this and probably have a chat with @EdMoffatt and/or @winslet to get their thoughts.

**Comment by samjsmith** [comment] 2017-10-09 11:09
Discussed with @caroline-church and @EdMoffatt and the decision here is to try to arrive at a solution that does not prefill any strings that have a regex associated with them, so that at least users can see the  skeleton structure of the object. However, we would like validation to run and prevent creation of objects that don't meet the regex criteria.
So it seems like an issue of turning validators on/off at the right moment.

**Comment by samjsmith** [comment] 2017-11-08 13:18
I think a combination of #2391 and #2413 should address this issue and that mean that it can be closed now.  Playground will auto generate Identifier fields if there is no regex constraint.

**Closed by samjsmith** 2017-11-08 13:18 UTC
Labels: bug, model, P2, playground
