### ISSUE TITLE
BNA export faulty on Safari

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#1281] opened 2017-06-15 10:40 UTC
When exporting a .BNA from the Playground in Safari, instead of getting <business_network_name>.bna as the exported file, you get Unknown (no file extension).

## Context
Happens either with local or web Playground, testing latest unstable build and also latest stable build.

## Expected Behavior
The file exported should be <business_network_name>.bna

## Actual Behavior
The file exported is Unknown (of Unknown-1 etc. on successive exports).

## Steps to Reproduce
1. Open Playground in Safari
2. Hit Export
3. Check the file in your Downloads directory

## Existing issues
Couldn't spot any!

## Context
Not a big effect as I just renamed it to "Unknown.zip" and extracted, and could still continue what I was doing.  Unlikely your typical user would think to do that though!

## Your Environment
Safari on MacOS, latest stable and unstable builds as at Jun 15, 11:30am

**Comment by caroline-church** [comment] 2017-06-15 10:48
This works fine with safari 10.1.1, i think we have seen this issue before with older versions of safari

**Comment by EdMoffatt** [comment] 2017-06-15 10:54
I'll upgrade and test again!  I'm on 10.0.1.

Worth noting that the "things" exported can be imported via Browse...  But not via drag/drop - so they sort of are and aren't valid business network archives

**Comment by sstone1** [comment] 2017-06-15 18:56
Closing as a dupe of:
Export BNA from Playground on Safari does not name the file #407

@EdMoffatt can you raise another issue for the browse bug please?

**Closed by sstone1** 2017-06-15 18:56 UTC
Labels: bug, duplicate, playground, prereq
