### ISSUE TITLE
playground appears to hang when deploying the sample network when using a hlfv1 profile

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1086] opened 2017-05-25 16:19 UTC
This may also apply to an hlf 0.6 profile as well.

I started playground and created an hlfv1 profile. I select this profile to use and select my identity
the deploy actually works however playground keeps the dialog up with the busy spinner saying it's deploying the network. (I can see it has really deployed as the connector reports all is ok).

If I then refresh the page,  I see the hlf v1 profile is selected ok and I can then deploy a sample network without any problem

Assigned initially to Caroline as she is aware of the problem and could add more detail or correct my description.

**Comment by sstone1** [comment] 2017-05-30 11:33
@caroline-church this is probably a duplicate of #1058 so I've assigned both to you.

**Comment by caroline-church** [comment] 2017-06-01 08:06
done so closing

**Closed by caroline-church** 2017-06-01 08:06 UTC
Labels: bug, P1, playground
