### ISSUE TITLE
Tutorial link on Composer Playground points to 404

### ISSUE THREAD

**Issue by sudheesh001** [hyperledger/composer#2790] opened 2017-11-21 09:05 UTC
Clicking on the `Playground Tutorial` link on https://composer-playground.mybluemix.net/login takes the user to the following page https://hyperledger.github.io/composer/tutorials/playground-guide.html which is broken and a 404.

## Expected Behavior
The link actually takes the user to the tutorial. https://hyperledger.github.io/composer/tutorials/playground-tutorial.html

#### Homepage link
![composer-initial](https://user-images.githubusercontent.com/4545925/33063659-1eb0a852-cec9-11e7-9ff8-9f5629d4fa8c.PNG)

#### Error
![composer-error](https://user-images.githubusercontent.com/4545925/33063536-bcc8f784-cec8-11e7-9254-7fb6fdefd05a.PNG)

## Steps to Reproduce

1. Go to https://composer-playground.mybluemix.net/login
2. Look for `Get started with the basic-sample-network, or view our Playground tutorial` with the link on `Playground tutorial`.
3. Click on the link
4. Takes the user to a 404 page.

**Comment by sudheesh001** [comment] 2017-11-21 09:08
While this looks like it's fixed in the code, it looks like the deployment doesn't reflect the latest changes.
https://github.com/hyperledger/composer/blob/d74d712b9fa81822121a4d98e2b81a5d850cbd23/packages/composer-playground/src/app/common/identity-card/identity-card.component.html#L43

**Comment by awjh-ibm** [comment] 2017-11-21 10:36
I am unable to reproduce this issue. Does performing a hard page reload fix the issue?

**Comment by sudheesh001** [comment] 2017-11-21 11:11
Yes I performed a hard page reload and also opened it in a new private browsing window and even in another browser that I rarely use. The steps to reproduce still seem valid
1. https://composer-playground.mybluemix.net/login
2. Click on the required link and it takes you to a 404

**Comment by awjh-ibm** [comment] 2017-11-21 11:28
Appoligies I have followed steps to reproduce correctly now (I was following the link in the footer). This issue also exists for the following the link in the welcome to playground popup as well as in the example business network card. This issue will be resolved in the next release.

**Closed by awjh-ibm** 2017-11-21 11:28 UTC

**Comment by sudheesh001** [comment] 2017-11-21 12:58
I am not sure closing the issue is the right thing to do, the code might have been fixed but it'd be good to close this once the release is done and the new version is deployed. I am in favor of keeping this open until then.
