### ISSUE TITLE
A user can switch between files as needed to work on a Business Network Definition

### ISSUE THREAD

**Issue by EdMoffatt** [hyperledger/composer#2309] opened 2017-10-06 14:23 UTC
## Context

There are a few existing issues open around the fact that it is very easy for Playground to "throw away" your edits unexpectedly, and that there is no ability to import BNAs with errors to then fix, or no ability to "save" a working copy that you may or may not later deploy to one or more places...

There's too much work to be covered as Issues for now, so proposing a 2-prong approach.

Prong 1: this issue!
A P2 bug to fix the very most frustrating parts of the behaviour

Prong 2: consolidated Epic
I'm going to close the existing issues that nobody is actively working on, and raise a new Epic collecting together all the info tht's needed for when we come to work on the "complete fix".

## Issue

A user is working on a Business Network Definition in Playground.  They add a new Transaction to the Model file, then switch to the Script file to write the JavaScript...  They get part way through typing it out, but they can't remember what they called one of the variables...  So, with their .js file currently in an error state, they flick back to the .cto file to check what it was.
At the moment, when they return to the Script file, they'll find all the changes they'd made gone, because navigating off it whilst it's in error state causes it to revert to the latest deployed good version.

## Desired Fix

Allow a user to switch between files in the Define tab without any that are in error state being "reverted" to older versions.  This probably means we need to store the latest edits to all files in memory.

We *will* go further with this fix, but for now this seems a good minimal required to fix the worst of the bug.  So to be explicit...
- If the user goes back to the My Business Networks screen, any un-deployed changes will still be lost.
- If the user switches to any other tab (e.g. Test panel), any un-deployed changes will still be lost.
Obviously there are better versions of these behaviours, and that's what we shall explore in the Epic - for now, lets just try to make the basics of writing a Transaction Processor Function workable ;)

**Comment by caroline-church** [comment] 2017-10-07 19:37
closing as this is a duplicate of hyperledger/composer#1530 which is currently being worked on

**Closed by caroline-church** 2017-10-07 19:37 UTC
Labels: bug, P2, playground
