### ISSUE TITLE
Composer network Upgrade should only be disallowed if there is an incompatible change to the runtime

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#2513] opened 2017-11-01 08:13 UTC
Currently the runtime version changes in line with composer releases, even if a minor version change doesn't result in an incompatible change to the runtime. This then stops network upgrades that would be possible as it uses semver checking.

There is a bigger story to support data migration where possible between runtime versions but as a first start we should look to allow upgrades in a different manner.

**Comment by sstone1** [comment] 2017-11-08 09:08
Closing as duplicate of #2097. We have more important things to worry about at the moment then migration between our 0.x.y releases.

**Closed by sstone1** 2017-11-08 09:08 UTC
Labels: enhancement, runtime
