### ISSUE TITLE
Minor niggles in Angular Generator

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer#3826] opened 2018-04-12 10:31 UTC
Usability issue:
- When I create an angular application, selecting to also create a REST server to connect to, when specifying the answer to 'use namespaces or not', the same question is displayed (but skipped over) in the console output.

**Comment by zachgoll** [comment] 2018-05-14 15:42
@nklincoln I'm not able to reproduce this.  Has it been fixed in `v0.19.5`?

**Comment by KaiUsher** [comment] 2018-05-24 09:09
Both @EllisHenderson and I cannot recreate this either so closing the issue.

**Closed** 2018-05-24 09:10 UTC
Labels: P3, bug, generator
