### ISSUE TITLE
Lab 1: Create a Hyperledger Composer solution not working

### ISSUE THREAD

**Issue by pdey6** [hyperledger/composer#2851] opened 2017-11-27 15:16 UTC
In 'IBM Blockchain Foundation Developer' course, on the section Lab 1: Create a Hyperledger Composer solution, there is a button called 'Start the Lab'. The link fails on clicking this button.

**Comment by sstone1** [comment] 2017-11-27 15:18
Duplicate of #2843 
> The IBM site needs updating; I've asked the IBM team responsible for this to take a look.

**Closed by sstone1** 2017-11-27 15:18 UTC
Labels: duplicate
