### ISSUE TITLE
Playground: Asset Registries don't update when the model changes

### ISSUE THREAD

**Issue by EdProsser** [hyperledger/composer#489] opened 2017-03-16 12:14 UTC
## Context

When a participant type is added to the business network definition, it appears in the Test tab so you can create participants of that type. If you then update the definition again to remove that participant type, the Test tab doesn't update to remove the participant type.

## Expected Behavior
Participant types removed from the .cto file should be removed from the Test tab UI.

## Actual Behavior
Participant types removed from the .cto file remain in the test tab menu.

## Steps to Reproduce
1. Open playground and import a sample. 
2. Create a new participant type in the `.cto` file and Update to redeploy.
3. Open Test tab to ensure participant type now exists. 
4. Go back and edit `.cto.` file to remove the participant type. Update again.
5. Open Test tab. Participant type still exists.

## Context
May cause UI cluttering for users who are trying to extend samples to suit their business needs.

## Your Environment
Seems to work on all versions of playground. Tested on Windows with Chrome.

**Comment by EdMoffatt** [comment] 2017-03-28 08:28
Just  to quickly check the "as intended" behaviour before I answer... ;)
In the case that the registries had some stuff in them, it sounds like a good behaviour.  And then (2) sounds like an excellent extension of that: to "clean up unused registries" if a user started playing with a sample, gradually transitioned it into their own solution, and now no longer needs all those sheepgoats.

Can we differentiate between "unused" and "unused AND empty"?  Behaviour (3) would be good on registries where no objects were were ever created, as there's no reason to keep them around to "re-access" the assets/participants if they're re-added to the model later (it'd be equivalent to just create a new registry with that name).

My gut is telling me that a thing the serialiser fails to find definitions for might be tricky to tell whether it's empty though, right?

**Comment by sstone1** [comment] 2017-06-07 13:31
Duplicate of: As a user, I need to add non-optional fields to asset definitions for which existing assets already exist #601

**Closed by sstone1** 2017-06-07 13:31 UTC
Labels: architecture, enhancement, playground, runtime
