### ISSUE TITLE
Table of Contents / outline pane in the docs is very frustrating to use

### ISSUE THREAD

**Issue by radariii** [hyperledger/composer#2360] opened 2017-10-12 13:38 UTC
It's really frustrating the the table of contents pane on the left side of the Composer docs auto-expands when you mouse over it. 

## Context
When you expand a section in the left-pane, the content no longer fits vertically on the screen, introducing the need to scroll to see the other sections or navigate between them.  But because you need to actually have your mouse pointer in that pane in order to scroll it, you end up accidentally expanding sections all over the place that you don't want to.  And because the expanded sections push all content below them down, you now have to scroll extra far to get to the top-level item you were looking for.  But then as soon as you get on the item you wanted in the first place (thus mousing-out of the section above it) the upper section collapses and everything scrolls back up!!  This is very frustrating for developers who need to move easily through the docs.

This problem is exacerbated by the fact that when you select a sub-item in the TOC, the entire page refreshes and the TOC pane is scrolled back to the top, which means that you MUST go through that frustrating scrolling experience all over again for every new page you want to go to.

## Expected Behavior
Probably the easiest thing to do is to take out the 'expand-on-hover' functionality and replace it with 'expand-on-click'.

## Actual Behavior
See above

## Possible Fix
See above

## Steps to Reproduce
You will not have any problem reproducing this behavior... Just put your developer hat on and pretend that you need to find information from more than one page in the documentation, particularly the API reference section where it is typically to want to bounce quickly between pages.

**Comment by EdMoffatt** [comment] 2017-10-16 19:31
Looks like a duplicate of #2327 to me - closing as dup.
Totally agree with the observations and suggestions here :)  2327 is already one of our top priority issues, so it's useful to hear of another person who really wants it fixed!

**Closed by EdMoffatt** 2017-10-16 19:31 UTC
