### ISSUE TITLE
Build fails occasionally on running hlfv1 system tests

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#788] opened 2017-04-28 17:29 UTC
```  
1) Transaction (asset specific) system tests should submit and execute a transaction that updates an asset with a relationship in the transaction in an asset registry:
     Error: Error executing chaincode: Failed to execute transaction (Timeout expired while executing transaction)
      at /home/travis/build/hyperledger/composer/node_modules/grpc/src/node/src/client.js:434:17
```
This could be related to the change to duktype. It should be investigated though to see what the intermittent cause is.

**Comment by sstone1** [comment] 2017-04-28 17:32
Duplicate of #775 HLFv4 chaincode sporadically crashes

**Closed** 2017-04-28 18:45 UTC
