### ISSUE TITLE
As a user I should have access to the glossary

### ISSUE THREAD

**Issue by dselman** [hyperledger/composer#28] opened 2017-02-01 09:24 UTC
The glossary is current incomplete (included tbc):
https://fabric-composer.github.io/reference/glossary.html

We either need to remove it or finish it.

**Comment by EdProsser** [comment] 2017-05-02 14:12
This is a duplicate of #255. So I'm gonna close this one and work in the other.

**Closed by EdProsser** 2017-05-02 14:12 UTC
Labels: docs
