### ISSUE TITLE
Composer Playground : Transaction List not following ACL Rules from Tutorial

### ISSUE THREAD

**Issue by msyk659** [hyperledger/composer#3959] opened 2018-05-03 02:52 UTC
If you follow the Access Control Tutorial found at : https://hyperledger.github.io/composer/latest/tutorials/acl-trading.html , at Rule 3 (R3_TradersSeeOwnHistoryOnly), Once including the rule and deploying the network again, Traders are still able to see all Trade transactions even if they are not the participating trader for that transaction.

## Context
In the Tutorial you are walked through implementing the Setup for a Business network with 1 Partitcipant (Traders),1 Asset (Commodities) and 1 Transaction (Trade). 
Rule 3 (TradersSeeOwnHistoryOnly) in the tutorial is supposed to limit traders to only be able to view transaction invoked by themselves. How ever the observed results are not the same as those documented in the tutorial. Traders Can still see all Trade Transactions.

## Expected Behaviour
Once implementing the rule R3_TradersSeeOwnHistoryOnly as provided by the tutorial, Traders should not be able to view transactions that they are not the invoking Participant for.

## Actual Behaviour
Traders are able to view all transactions in the All Transactions Area of the Hyperledger Composer Playground.

## Possible Fix
Update the Tutorial Rules if changes have been made to the definitions of ACL Rules, or fix the logic behind enforcing ACL Rules for Identities in the Transaction Log (in Composer Playground).

## Steps to Reproduce
Follow the tutorial at https://hyperledger.github.io/composer/latest/tutorials/acl-trading.html and progress through  Rule 3.

This includes submitting a Trade transaction As the identity tid2 and transferring resource:org.example.trading.Commodity#EMA to "newOwner": "resource:org.example.trading.Trader#TRADER2".

Rule R3_TradersSeeOwnHistoryOnly Does not appear to have the intended effect. 
```
rule R3_TradersSeeOwnHistoryOnly {
  description: "Traders should be able to see the history of their own transactions only"
  participant(t): "org.example.trading.Trader"
  operation: READ
  resource(v): "org.hyperledger.composer.system.HistorianRecord"
  condition: (v.participantInvoking.getIdentifier() != t.getIdentifier())
  action: DENY
}
```
When switching Identity to tid5, tid5 can see the transaction performed by tid1 in All Transactions.

 ## Context
Cannot follow the tutorial, as expected results and actual results differ.

## Your Environment
 Environment:  https://composer-playground.mybluemix.net/
 Browser Used : Edge
 Operating System : Windows 10
 Date : 3/05/2018

**Comment by zachgoll** [comment] 2018-05-05 01:14
@msyk659 Although I have never used the Microsoft Edge browser with the Composer playground, I am not seeing the same issue.  I followed the tutorial end to end and everything works as expected.  Make sure that you are pasting the new rules at the TOP of the permissions file, and maybe try the tutorial again?

**Comment by mahoney1** [comment] 2018-05-15 08:45
@msyk659  Echo what @zachgoll has written. The issue is likely 'where' you pasted your rule - the order of rules is important, in evaluation terms. Closing this but feel free to open if you have a continued issue, thanks

**Closed by mahoney1** 2018-05-15 08:45 UTC
