### ISSUE TITLE
As a contributor I need instructions on how to commit code

### ISSUE THREAD

**Issue by fenglianxu** [hyperledger/composer#161] opened 2017-02-13 14:44 UTC
Document the basic use of Git and GitHub: branches, forks, pull requests and Travis CI.

**Comment by caroline-church** [comment] 2017-03-17 15:23
@mbwhite can we call this complete or is there more stuff to do?

**Comment by EdMoffatt** [comment] 2017-04-11 09:33
As part of a GitHub "lets get super organised" drive...

- Leaving this one as an Issue, as it doesn't seem large enough to convert to an Epic and split down
- Un-assigning @sstone1 , since he's on holiday and shouldn't be working ;) This will mean it appears as open for anyone to pick up
- Changing to the Playback 4 milestone, so that we can track the current playback tasks in ZenHub (ZenHub doesn't play so well with Projects!)

This one seems somewhat linked to #213 ?
First task should be to define where we want these instructions to live, and whether it's a different place from the Contributors guide (main readme.md on the fabric-composer GitHub project seems another possible option?  Though a contributor guide that covers the basic how and then the best practices in the same place seems the best option to me).

**Comment by sstone1** [comment] 2017-04-24 10:25
Duplicate of #213.

**Closed by sstone1** 2017-04-24 10:25 UTC
Labels: docs, user story
