### ISSUE TITLE
Historian screen doesn't handle reduced width well

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/composer#2205] opened 2017-09-22 10:46 UTC
Historian adds ellipses if the text won't fit, but there's no hover to see the full text...

![image](https://user-images.githubusercontent.com/3535067/30741176-b6f315ae-9f8b-11e7-98f6-b91dadf7f144.png)

**Comment by sstone1** [comment] 2017-09-22 15:05
Duplicate of:
Historian content is cramped and ellipsis used for UUID and action link #1895

**Closed by sstone1** 2017-09-22 15:05 UTC
Labels: bug, design, duplicate, playground
