### ISSUE TITLE
Playground difficult to navigate on small screens

### ISSUE THREAD

**Issue by mqmatt** [hyperledger/composer#1819] opened 2017-08-09 15:49 UTC
## Context
When running Playground on a small screen (e.g. a projector) the “Cancel”, “Create New” and "Generate test data" buttons are hidden entirely from the modal dialogs (e.g. create/update asset), and the user has to scale the web page in order to find them.

## Expected Behavior
The buttons should always be visible regardless of screen size.

## Actual Behavior
On a small display the buttons cannot be seen.

## Possible Fix
Ensure that these action buttons are always displayed at the expense of JSON editor space, or maybe provide the ability to resize or move the modal dialogs throughout Playground 

## Steps to Reproduce
You can reproduce this issue by making the browser window smaller and then trying to create an asset or participant.

## Your Environment
* Version used: Playground 0.11.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox

**Comment by caroline-church** [comment] 2017-10-04 16:12
this is a duplicate of https://github.com/hyperledger/composer/issues/2233 so closing

**Closed by caroline-church** 2017-10-04 16:12 UTC
Labels: bug, P2, playground
