### ISSUE TITLE
Validation within Playground removes my changes

### ISSUE THREAD

**Issue by Tobias-Hunter** [hyperledger/composer#1498] opened 2017-07-06 11:03 UTC
## Context
Changes to files can be lost, when switching between files

## Expected Behaviour
I shouldn't lose my changes! 😎

## Actual Behaviour
I lose my changes! 😢

## Steps to Reproduce
![issue v0 1](https://user-images.githubusercontent.com/25635381/27907952-88973870-6241-11e7-9179-29008e948563.gif)
1. In Playground, add a breaking change to a .cto file
2. Switch to a different file
3. Switch back to your original file
4. Changes in the .cto file will be gone!

**Comment by markcastle3** [comment] 2017-10-02 13:42
Closing this as its a duplicate of #1530

**Closed by markcastle3** 2017-10-02 13:42 UTC
Labels: bug, playground
