### ISSUE TITLE
Find all and filter with json not working correctly

### ISSUE THREAD

**Issue by paulxuereb** [hyperledger/composer#2237] opened 2017-09-27 03:29 UTC
Since updating to composer v0.13.0 i am experiencing errors with 'find all' and 'filter based' API calls. These worked correctly on the previous version

## Context

Composer's REST API seems to have a bug with filtering in the latest release. My records exist in the asset registry, but are not showing up in GET API calls

## Expected Behavior

Running the 'find all instances of the model matched by a filter from the data source' should return all instances, either providing a filter, or omitting a filter

## Actual Behavior

Running the 'find all instances of the model matched by a filter from the data source' should returns no records when omitting a filter (eg: http://localhost:3000/api/Auctioneer, and no records when including a filter http://localhost:3000/api/Auctioneer/?filter={"email":"a"}

## Steps to Reproduce

1. Create a multi org, multi peer fabric network
2. Import identities from the fabric network into composer using composer identity import
3. Create a composer connection profile for org1 & org2
4. Download the composer sample project carauction-network
5. Composer archive create ... for the carauction-network
7. Composer runtime install ... for org1 for the network carauction-network
8. Composer runtime install ... for org2 for the network carauction-network
9. Composer network start ... on org1
10. Create the rest API on org1 using composer-rest-server ...
11. Browse to http://localhost:3000/explorer, list the operations for the Auctioneer object
12. Create a new instance of the Auctioneer model, setting the parameters appropriately, wait for response code and body to indicate success 
13. Execute the operation GET /Auctioneer/{id} 'find a model instance by the {{id}} from the data source', specifying the email address of the record you created in step 12 in the id parameter. eg: name@email.com. Calls http://localhost:3000/api/Auctioneer/name@email.com - should return the record correctly
14: Run the GET /Auctioneer 'find all instances of the model matched by a filter from the data source' operation, passing no parameter in the filter field. This calls http://localhost:3000/api/Auctioneer/ , should return the record created in step 12 - but doesn't
15: Run the GET /Auctioneer 'find all instances of the model matched by a filter from the data source' operation, passing the parameter {"email":"name@email.com"} in the filter field. This calls http://localhost:3000/api/Auctioneer/filter={"email":"name@email.com"} , should return the record created in step 12 - but doesn't

## Existing issues
I've posted this on rocket chat, but not seen any responses yet

N/a

## Context

I am trying to interact with a network i have built, which has the same results as the bug described here, but thought that it was worth listing a sample project which has the same result.

This worked fine before upgrading composer today

## Your Environment

Hyperledger Fabric v1
Composer v0.13.0

**Comment by paulxuereb** [comment] 2017-09-27 04:46
Additional update, i have tried to replicate this issue using the standard (single CA, single peer) composer docker setup (https://github.com/hyperledger/composer-tools/tree/master/packages/fabric-dev-servers/fabric-scripts/hlfv1) and the issue described above is not able to be reproduced. So it must be related to my multi org/ca, multi peer network setup

**Comment by dselman** [comment] 2017-09-27 06:29
The `composer-rest-server` does not (yet) support filters, however doing a GET request without filters should return all instances.

**Comment by dselman** [comment] 2017-09-27 06:31
Filter support is being worked on under #2106. I am going to close this as you indicate that you cannot reproduce the issue without a filter set. Please create a new issue if you can reproduce the multi-org issue.

**Closed by dselman** 2017-09-27 06:31 UTC

**Comment by paulxuereb** [comment] 2017-09-27 06:44
@dselman i think that you misinterpretted what i wrote in step 14, having no filters on a multi org network returns no results. Will open a new case, excluding the filters
