### ISSUE TITLE
Use Playground to upgrade business network deployed as Fabric chaincode

### ISSUE THREAD

**Issue by bestbeforetoday** [hyperledger/composer#3241] opened 2018-01-25 16:34 UTC
**As a** business network deployer
**I want** to use Playground to deploy a new version of a deployed business network
**so that** I can use a graphical UI to iterate on a business network implementation

Upgrade will work differently and be a more heavyweight operation:
* Upgrade existing app with a version number change; or
* Entirely new business network install

Needs design input on Playground experience to reflect the underlying deployment mechanism.

**Comment by davidkel** [comment] 2018-01-30 11:36
The proxy connector and server will require updates to the signature change of install and start.

**Comment by winslet** [comment] 2018-02-19 11:24
@EdMoffatt's first mockups can be found here: https://xd.adobe.com/view/d0dd8ae6-2d03-4714-acb3-75dd9b86042c/

@bestbeforetoday do these make sense thus far? Looks like ill need to give it a pass on the visual front. Do we have any ideas on when you'll need these by?

**Comment by EdMoffatt** [comment] 2018-02-26 13:08
Assigning this one over to @bestbeforetoday to take a look and see whether we've got what's needed in the low-fi designs ready for Sam to start on the hi-fi work?

**Comment by EdMoffatt** [comment] 2018-03-01 10:11
Since this one is in the 1.0 plan (I think?!), lets kick off the few bits that need deciding on it :)  

Firstly a thing that I remember talking to @caroline-church about: the mockups only show a few steps in the "progress feedback" (e.g. "installing new chaincode" "performing chaincode upgrade" etc.).  Caroline thought that there should be more granular feedback we can get, so we should figure out what progress-updates we can get back from the APIs and then list it in the issue here, so we can decide which ones should be passed on as info to the waiting user :)

Secondly, verifying that the low-fi is indeed fit for the purposes we need - can I nag @sstone1 or @caroline-church  or @bestbeforetoday to take a look please?  I'd like to assign @winslet to take a hi-fi pass at the styling of these elements, but I don't want to do that before we agree that this solves the problem in principle :)  Cheers!

**Comment by caroline-church** [comment] 2018-03-01 10:15
The designs look good. I spoke to @davidkel about more granular feedback and he said that it wasn't possible to get more detailed feedback.

**Comment by EdMoffatt** [comment] 2018-03-02 12:05
Updated to cover some more edge cases that @jt-nti helped me think about yesterday :)  We now have a slightly different way of editing just the version number, a different way of getting to package.json, and an error state for if you try to put in a lower version number.

What's the link?
The link's the same!
That link again is: https://xd.adobe.com/view/d0dd8ae6-2d03-4714-acb3-75dd9b86042c/

(Sung to the tune of the "Mr. Plow" song from The Simpsons, tho I admit the scansion somewhat falls down when you try to sing the full URL)

**Comment by jt-nti** [comment] 2018-03-05 10:57
@EdMoffatt just to confirm, the *Import/Replace* action below the *Update* button will be removed as part of this work:

![image](https://user-images.githubusercontent.com/3535067/36971467-ce526872-2063-11e8-98b1-b2c66c3f3db8.png)

**Comment by EdMoffatt** [comment] 2018-03-05 12:57
Yes, confirmed @jt-nti :)  We should lose import/export but keep export
(import/export gets confusing when versions matter, and heading back a screen to deploy new business networks is the new way of doing this).

Also, @mahoney1 - can I talk about this one the next community call pleeeease?

**Comment by mahoney1** [comment] 2018-03-05 16:02
@EdMoffatt most definitely - 10am (this Weds 7/3)

**Comment by jt-nti** [comment] 2018-03-20 16:35
Design updates...

Initial rough outline from @EdMoffatt:

![image](https://user-images.githubusercontent.com/3535067/37668041-685a12d2-2c5b-11e8-8296-74f09030070e.png)

Updated hifi from @winslet (ok, it's a screen shot!):

- lightened background of update network section and continue background colour behind action buttons (same as file highlight)
- reduce spacing above/below each file title/name
- outline action button section
- fix action button alignment (not shown)
- reduce spacing in update network section (not shown)
- no need to switch to package.json when editing version (not shown)

![image](https://user-images.githubusercontent.com/3535067/37668077-7d14f246-2c5b-11e8-88ca-082acc9c5e08.png)

Likely to need further rework in the return of the business network card epic: attack of the fabric deployment design

**Comment by winslet** [comment] 2018-03-20 17:09
Working on the modal needed @caroline-church has already put work into, this is the decision we came to:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/13980028/37670512-69bf91c8-2c61-11e8-9c19-6eadb8827ac1.png">

I have made an attempt at the wording on this page, but please feel free to add more/change as you see fit.

**Comment by bestbeforetoday** [comment] 2018-03-21 09:26
@winslet @EdMoffatt On the _Upgrade business network_ dialog above, what do we expect the behaviour to be when the user has:
1. Only one business network card that is usable for installation and upgrade.
1. No business network cards that are usable for installation or upgrade.

The first is going to be the typical case where users have deployed a business network within Playground, and the second will be the typical case where the user has been given a participant card by somebody else who has set up the network. I think it will be very unusual for the user to have a choice of cards they can actually use.

**Comment by winslet** [comment] 2018-03-21 09:50
Hey @bestbeforetoday,

1. From the conversations yesterday between @caroline-church @jt-nti and myself, we will most times have 2 cards in that dropdown, the one you're connecting in with and then an 'admin' card used to deploy. We will by default pre-select the option which contains 'admin' rights (99% of the time this will be the one used to deploy). If there is only one card then we give them only one option in the drop down 👍 
2. As I understand it, if the user is trying to use a card without the correct permissions, we will not actually know this until we try. If this is not the case then we should be "greying out" the Upgrade button in the left hand nav of the editor in the first place, to stop people even getting to this screen. @caroline-church @jt-nti please correct me if im wrong here. However you raise a good point - if this does error, can we provide feedback to the users due to the error? (not sure if we get this info back from Fabric) If we do I should definitely mockup an error notification explaining what has happened and why.

This is all a bit of a 💩 experience as it is, we need to come back and fix this properly asap.

**Comment by caroline-church** [comment] 2018-03-21 09:54
The install drop down will display cards with the "PeerAdmin" role and the upgrade drop down will show cards with the "ChannelAdmin" role. Most of the time there will only be one card in each drop down. You are correct @winslet that we have to try the upgrade to know that the user can't do it. If there are no cards available they will still be able to press the upgrade button but a message will appear saying that they don't have a card with the correct role. If the upgrade fails an error message will say why it failed

**Comment by jt-nti** [comment] 2018-03-21 09:55
> we will most times have 2 cards in that dropdown, the one you're connecting in with and then an 'admin' card used to deploy

It's extremely unlikely that there will be two different cards for this dialog. As @bestbeforetoday says, you're either going to have the same card selected twice (the automagic card with PeerAdmin and ChannelAdmin markers), or there will be no suitable card available.

As you say, there is no way to tell if any of the cards are actually going to work (have the correct authority, or have not been revoked) so the Playground must go on the assumption that cards are still valid and the PeerAdmin and ChannelAdmin markers are correct.

**Comment by winslet** [comment] 2018-03-21 09:58
Great, so if im getting this correct, we could collapse the drop downs into one? Or even just display the card name we're going to use and not have any drop downs at all? 

Im a little confused about this last idea as I was under the impression we probably needed to let someone select a card which has the right role following yesterdays discussions?

**Comment by caroline-church** [comment] 2018-03-21 10:00
No we do need both drop downs as they could be separate cards and we let them have separate cards for deploy. Each drop down will display the cards with the correct roles.

**Comment by bestbeforetoday** [comment] 2018-03-21 11:06
@winslet Something to consider for future design re-visits... If the user does not have any cards suitable for installing/upgrading the business network, they might be disappointed to only discover this when they click the **Upgrade** button _after_ spending time changing the model, transactions logic, permissions etc. I guess they can at least save their changes at this point but I think I'd prefer to know up-front that I wouldn't be able to deploy any changes I made.

**Comment by davidkel** [comment] 2018-03-21 11:53
I'm going to take a stab at the scenarios that are intented to be supported here, but please add to it if I miss any
- Web Profile (not affected)
- Real Fabric. Playground instigates business network install/start
- Real Fabric. User Connects to running business network after being given a card
  - User has no credentials to perform install/upgrade
  - User only has credentials to perform install
  - User only has credentials to perform upgrade
  - User has credentials to perform install/upgrade
- Real Fabric. User has multiple fabric admin cards (Not business network cards) that can perform install/(start/upgrade) or both on the same fabric

Finally there is one really big caveat when you want to work with a real fabric. Because install+start and install+upgrade are merged together as a single action. There could be problems connecting to a multiorg fabric and performing a deploy or update as the install action will ONLY install to the organisation defined in the install card chosen to perform the install. This could lead to start/upgrade failures or worse Peers that try to upgrade/start but don't have the correct business network leading to request failures.

The assumption also being made is that playground will be used to connect to fabrics which are not simple single org development fabrics that only require a single card or 2 cards, 1 for install and 1 for start/upgrade.

These are all possible scenarios, but it should be considered what is the roll of playground within a development environment, test environment and production environment. One option to consider is if you don't have the right support to perform upgrade, then maybe the develop tab is not displayed and all you can do is test.

**Closed** 2018-03-27 20:54 UTC
Labels: design, user story
