### ISSUE TITLE
REST problem with wallet

### ISSUE THREAD

**Issue by caroline-church** [hyperledger/composer#1793] opened 2017-08-08 13:08 UTC
If you are using passport authenitcation on the rest server then try and add a identity to the wallet the sample json includes the wallet id. If you have this set the request will fail

**Comment by sstone1** [comment] 2017-08-17 22:00
Duplicate of the LoopBack bug described in:
Example data for transactions in rest server include {"transactionId": "string"} #663

**Closed by sstone1** 2017-08-17 22:00 UTC
Labels: bug, duplicate, P2, rest
