### ISSUE TITLE
Adding datasource to the Composer REST Server leads to Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin)

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer#2455] opened 2017-10-24 10:31 UTC
## Context
I created an image from hyperledger/composer-rest-server using this Dockerfile:
FROM hyperledger/composer-rest-server
RUN npm install --production  loopback-connector-mongodb  && \
    npm cache clean && \
    ln -s node_modules .node_modules

Then ran
docker build -t hyperledger/composer-rest-server-persistent .

In envvars.txt I defined environment variables to run with docker run. I use the VLN as my business network. I peform two configurations:

1. No datasources is specified in envvars.txt. docker run looks like this:
docker run \
 -d \
 --name rest-plain \
 --network composer_default \
-v /<myhome>/composer-sample-applications/packages/vehicle-lifecycle/composer-data-latest/.composer-connection-profiles:/home/composer/.composer-connection-profiles \
 -v /<myhome>/composer-sample-applications/packages/vehicle-lifecycle/composer-data-latest/.composer-credentials:/home/composer/.composer-credentials \
-e COMPOSER_CONNECTION_PROFILE=${COMPOSER_CONNECTION_PROFILE}      \
-e COMPOSER_BUSINESS_NETWORK=${COMPOSER_BUSINESS_NETWORK} \
-e COMPOSER_ENROLLMENT_ID=${COMPOSER_ENROLLMENT_ID}     \
-e COMPOSER_ENROLLMENT_SECRET=${COMPOSER_ENROLLMENT_SECRET} \
-e COMPOSER_NAMESPACES=${COMPOSER_NAMESPACES}     \
-e COMPOSER_AUTHENTICATION=${COMPOSER_AUTHENTICATION}     \
-e COMPOSER_CONFIG="${COMPOSER_CONFIG}" \
-p 3000:3000     \
hyperledger/composer-rest-server-persistent

docker logs rest-plain says:
0|composer | Added schemas for all types to Loopback
0|composer | Web server listening at: http://localhost:3000
0|composer | Browse your REST API at http://localhost:3000/explorer
[great!]

2. Datasource is specified in envvars.txt and "docker run" looks like this (-e COMPOSER_DATASOURCES added):
docker run \
 -d \
 --name rest-persistent \
 --network composer_default \
-v /<myhome>/composer-sample-applications/packages/vehicle-lifecycle/composer-data-latest/.composer-connection-profiles:/home/composer/.composer-connection-profiles \
 -v /<myhome>/composer-sample-applications/packages/vehicle-lifecycle/composer-data-latest/.composer-credentials:/home/composer/.composer-credentials \
-e COMPOSER_CONNECTION_PROFILE=${COMPOSER_CONNECTION_PROFILE}      \
-e COMPOSER_BUSINESS_NETWORK=${COMPOSER_BUSINESS_NETWORK} \
-e COMPOSER_ENROLLMENT_ID=${COMPOSER_ENROLLMENT_ID}     \
-e COMPOSER_ENROLLMENT_SECRET=${COMPOSER_ENROLLMENT_SECRET} \
-e COMPOSER_NAMESPACES=${COMPOSER_NAMESPACES}     \
-e COMPOSER_AUTHENTICATION=${COMPOSER_AUTHENTICATION}     \
-e COMPOSER_CONFIG="${COMPOSER_CONFIG}" \
**-e COMPOSER_DATASOURCES="${COMPOSER_DATASOURCES}"     \**
-p 3000:3000     \
hyperledger/composer-rest-server-persistent

Now docker logs rest-persistent says:
Error: chaincode error (status: 500, message: Error: The current identity has not been registered: admin)

The difference between 1 and 2 is only in the datasource configuration:
COMPOSER_DATASOURCES='{
  "db": {
    "name": "db",
    "connector": "mongodb",
    "host": "<myhost>"
  }

## Expected Behavior
Adding the datasource should not lead to Error: The current identity has not been registered: admin).

## Actual Behavior
Adding the datasource leads to Error: The current identity has not been registered: admin).

## Possible Fix
May be additional steps are required to configure registered identity (admin) in datasource. In this case, doc would be great.

## Your Environment

node --version
v6.11.4
npm --version
5.5.1
docker --version
Docker version 17.09.0-ce, build afdb6d4
docker-compose --version
docker-compose version 1.13.0, build 1719ceb

**Comment by LarissaAuberger** [comment] 2017-10-24 11:11
sorry, I forgot to mention that as host I configure the IP Address of my host machine (hope this is correct):
COMPOSER_DATASOURCES='{
"db": {
"name": "db",
"connector": "mongodb",
"host": "<ip address of my host>"
}

**Comment by sstone1** [comment] 2017-11-08 09:18
Duplicate of:
As a User I want to be able to use an BN card with already enrolled certs as the Discovery ID #2461

This wil be resolved in this weeks release.

**Closed by sstone1** 2017-11-08 09:18 UTC
Labels: duplicate

**Comment by johnjayasingh** [comment] 2017-11-28 06:25
@sstone1 Is this solved. Cause i am not able to resuse the card which was issued and working previously
