### ISSUE TITLE
Types inheriting from abstract types with 'identified by' clauses don't work in Playground Test tab

### ISSUE THREAD

**Issue by radariii** [hyperledger/composer#2538] opened 2017-11-02 22:46 UTC
The following model does NOT work when I go to the Test tab in Playground 0.14.3 and try to create a new instance of the participant btype.  When I try that, the New Participant window that shows up does not have any of the fields of my types listed.

namespace org.acme.model
abstract participant p1 identified by a1 {
  o String a1
}
participant p2 identified by a1 extends p1 {
  o String a2 
}

HOWEVER, if I change my model to the following, it works:

namespace org.acme.model
abstract participant p1 identified by a1 {
  o String a1
}
participant p2 identified by a1 extends p1 {
  o String a1
}

Here's a video showing the problem:
![composerplaygroundbug](https://user-images.githubusercontent.com/6818975/32353928-d038218e-bffd-11e7-896d-cae4c52e43e2.gif)

Also notice that there are artifacts from previously deployed versions of the model still showing on the left side of the playground test screen, but that's probably a different bug. :)

**Comment by awjh-ibm** [comment] 2017-11-08 09:28
Duplicate of issue #2564 and fixed in PR #2575

**Closed by awjh-ibm** 2017-11-08 09:28 UTC
Labels: bug, P2, playground
