### ISSUE TITLE
how to add elliptic curve encryption algorithm to hyperledger composer's smart contract?

### ISSUE THREAD

**Issue by zcyzhu** [hyperledger/composer#4555] opened 2018-12-17 11:37 UTC
How to add elliptic curve encryption algorithm to hyperledger composer's smart contract?  how do I add an elliptic curve encryption algorithm to the js file to implement the user's encrypted data on the composer-rest-server?

**Comment by davidkel** [comment] 2018-12-17 12:02
Closing as this is not a bug in composer and is already raised on stackoverflow here https://stackoverflow.com/questions/53772839/questions-about-the-hyperledger-composer-smart-contract which is a better place to engage the community.

**Closed by davidkel** 2018-12-17 12:02 UTC
