### ISSUE TITLE
As a Playground user if I swap between file views with errors I loose content

### ISSUE THREAD

**Issue by mbwhite** [hyperledger/composer#1238] opened 2017-06-12 08:29 UTC
## Context
If editing either a model file or a transaction function, and I swap to another view then the contents that where just being edited are lost. 

For example if I forget the name of the type in a transaction function, there will be an error. If I swap to view the model to check, my current changes are lost.  

## Expected Behavior

Even with errors should be able to swap to other views, but should be blocked from deploying.

## Context

This is very very frustrating!

**Comment by sstone1** [comment] 2017-06-12 10:06
Duplicate of:
Playground should warn a user if they navigate from "Define" without deploying #922

**Closed by sstone1** 2017-06-12 10:06 UTC
Labels: bug, duplicate
