### ISSUE TITLE
Possible small memory leak within composer runtime

### ISSUE THREAD

**Issue by davidkel** [hyperledger/composer#1721] opened 2017-08-01 12:32 UTC
Once #1712 goes into the build, you can still see memory in the chaincode container increasing. It but slows down as the memory size increases. One interesting experiment was to throw away the duktape VM by destroying the heap, this did stop memory from increasing however you can't do that as it would appear there are some outstanding timers even when the Composer object is supposedly returned to the pool, it will still process those timers.
With a pool of size 8, I saw memory go beyond 1Gb. The increment was quite slow at that point. If I throw away the heap memory stayed around 600Mb. 
More experimentation required to understand what exactly is going on here and how much of an impact it will have to long running environments.
It may also be related to the number of assets that have been created as the test creates random assets.

**Comment by ki0apa** [comment] 2017-08-03 18:25
I saw your commit on GitHub. I have one question. Let's say that I know I am making 20 requests at a time. Is it worth changing the `PoolSize` variable in constants.go to 20?

**Comment by davidkel** [comment] 2017-08-04 07:31
@ki0apa Increasing that number to 20 would increase the memory footprint. It is a performance vs memory decision. It only means the number that can be processed concurrently and will process the others when objects a returned to the pool.
It is possible to define the pool size during runtime install but this is more for benchmarking at the moment rather than something that will continue to be supported and is not documented currently.

**Comment by ki0apa** [comment] 2017-08-08 20:46
I found something in my personal investigation that might help.

I ran another test to see how the server performed after many requests in a single second. The memory leak was more severe in these tests. In other words, it takes fewer transactions to cause the docker container to crash when you are running more requests per second. 

My guess is that the objects that wait to be processed in the pool are not properly deallocated, but you probably understand the composer code better than I do.

**Comment by davidkel** [comment] 2017-08-09 09:43
@ki0apa Thanks for the update. 
I assume that the poolsize was set to 8 and were you using a version of the composer runtime with the first memory leak fix in ?

**Comment by ki0apa** [comment] 2017-08-09 11:45
@davidkel yes, I was using the most recent version of composer on npm and the poolsize was set to 8.

**Comment by ki0apa** [comment] 2017-08-09 15:01
I was just looking through the code. Does composer ever use `DestroyHeap` to clear some data in the duktape vm? Could this be a potential cause for the memory leak?

**Comment by davidkel** [comment] 2017-08-09 15:15
@ki0apa I experimented with calling DestroyHeap and it does keep memory under control so there is the potential for duktape to have a leak but it could still be our Go layer causing a leak in places. The problem with destroyHeap is knowing when to call it. It can't be called when the object is returned to the pool because even though it is returned to the pool, there are still timers running that will cause JS code to execute and until all the timers are completed you can't destroy the heap. Problem is there isn't a way to know when the timers complete as far as I can see.

**Comment by sstone1** [comment] 2017-08-17 21:10
This is not a P1 - the focus (for my team at least) is and will be on the work to deliver Node.js chaincode support to Hyperledger Fabric v1.1. This work will allow us to remove Duktape and all remaining Go code from Hyperledger Composer, which will either fix the problem or give us access to the proper diagnostic tooling we need.

**Comment by davidkel** [comment] 2017-10-25 19:02
Unlikely we will do this now as HLF 1.1 preview is just around the corner.

**Comment by sstone1** [comment] 2017-12-11 08:31
@csquan move up to v0.16.0, there are a lot of memory leak fixes in there. If the problem is not fixed, please see my comment from 17 Aug. Node.js chaincode is the priority and we have already switched the development branch onto Hyperledger Fabric v1.1.

Closing this issue.

**Closed by sstone1** 2017-12-11 08:31 UTC
Labels: investigation, P3, runtime
