### ISSUE TITLE
Composer-rest-server keeps loading when wrong card is uploaded to wallet

### ISSUE THREAD

**Issue by rohitkhatri** [hyperledger/composer#4142] opened 2018-06-12 11:39 UTC
I tried to start a `composer-rest-server` with existing `mongodb` database which I used earlier for a `composer-rest-server` and because of that, there were already some cards in the `db` added previously, and when I tried to use those cards on the new installation, and since the artifacts have been regenerated, the api is keep loading when called with those existing cards and eventually gives 504 error.

Please fix this.

**Comment by davidkel** [comment] 2018-06-13 13:13
I believe this to be a duplicate of 
https://github.com/hyperledger/composer/issues/3999

so closing

**Closed by davidkel** 2018-06-13 13:13 UTC
