### ISSUE TITLE
Error trying invoke business network. Error: No valid responses from any peers. Response from attempted peer comms was an error: Error: chaincode error (status: 500, message: ReferenceError: identifier 'error' undefined) 

### ISSUE THREAD

**Issue by Akash76** [hyperledger/composer#3594] opened 2018-03-13 18:52 UTC
## Code purpose
I have defined a bank logic containing transfer of amount from one address to another. And i have encountered following error 

## Context
![screenshot from 2018-03-14 00-24-35](https://user-images.githubusercontent.com/29705984/37363497-1ad0e9e2-271e-11e8-84de-43b3baf32429.png)
 Error trying invoke business network. Error: No valid responses from any peers. Response from attempted peer comms was an error: Error: chaincode error (status: 500, message: ReferenceError: identifier 'error' undefined) 

## Expected Behavior
It should be submitted as a transaction.

## Actual Behavior
giving an arror as mentioned above

## Your Environment
i am using mozilla firefox as my browser...And all other versions are up to date.

**Comment by alexdevassy** [comment] 2018-03-14 04:21
in your script file, in accounttransfer function did you use new Relationship(modelManager, classDeclaration, ns, type, id) ??

**Comment by dselman** [comment] 2018-03-14 08:15
factory.newRelationship

**Comment by Akash76** [comment] 2018-03-14 17:05
I got my mistake and the code is working well...Thank you

**Comment by davidkel** [comment] 2018-03-14 21:51
Closing as not an issue with Composer.

**Closed by davidkel** 2018-03-14 21:51 UTC

**Comment by tejakiranrayudu** [comment] 2018-04-19 06:47
Hi 

can you guys please post the answer for this issue.

**Comment by davidkel** [comment] 2018-04-19 07:16
@tejakiranrayudu you have made a programming mistake in your transaction function. You have used a  variable called `error` but not declared it.

**Comment by tejakiranrayudu** [comment] 2018-04-19 08:01
@davidkel 
my composer version is v0.16.6 

do i need to change to 0.19.1 to get rid of this issue

**Comment by davidkel** [comment] 2018-04-19 09:11
@tejakiranrayudu getNativeAPI is only available in 0.19.x

**Comment by davidkel** [comment] 2018-04-19 09:26
@tejakiranrayudu if you want to use getNativeAPI then you have to be on version 0.19.x

**Comment by tejakiranrayudu** [comment] 2018-04-19 09:33
@davidkel 

Very thanks and for 0.19.x do i need to create a new admin card from hlfv11 or it will work with hlfvl also ?

**Comment by davidkel** [comment] 2018-04-19 09:52
@tejakiranrayudu You should start from scratch. Cards built using 0.16.x are not compatible with 0.19.x. Business networks and their archives can be deployed using composer 0.19.x with no change however.

**Comment by tejakiranrayudu** [comment] 2018-04-19 15:08
@davidkel 

thanks for your reply.

i ran the command ./createpeeradmin.sh  on hlfv1 with composer version 0.19.0 and successfully created the admin card .

And then i tried deploying the project with the following commands 

composer network install --archiveFile tutorial-network@1.0.0.bna --card PeerAdmin@fabric-network
composer network start --networkName tutorial-network --networkVersion 1.0.0 --card PeerAdmin@fabric-network --networkAdmin admin --networkAdminEnrollSecret adminpw

Both the commands returned successful. After this i created a admin card and imported

and after that i ran the command "composer-rest-server"
and provided with the required details and getting an error at the end as 

Discovering types from business network definition ...
Connection fails: Error: Error trying login and get user Context. Error: Error trying to
enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]
It will be retried for the next request.
Exception: Error: Error trying login and get user Context. Error: Error trying to enroll
user or load channel configuration. Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]
Error: Error trying login and get user Context. Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]    at client.getUserContext.then.then.catch (C:\Users\Admin\AppData\Roaming\npm\node_modules\composer-rest-server\node_modules\composer-connector-hlfv1\lib\hlfconnection.js:393:34)    at <anonymous>    at process._tickCallback (internal/process/next_tick.js:188:7)

I found out the same like issue "https://github.com/hyperledger/composer/issues/3781".

Please help in sorting the issue one last one

**Comment by yeganehh** [comment] 2018-06-02 21:08
Hi 
i have problem with installing business network and i have encountered following error:
✖ Installing business network. This may take a minute...
Error: Error trying install business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 14 UNAVAILABLE: Connect Failed
Command failed

would you please help me?

**Comment by ramana459** [comment] 2018-06-09 17:05
Hi
I encountered similar issue, `connectionInvokeChainCode Error: Error trying invoke business network. Error: No valid responses from any peers.`
I observed a pattern, when the network is idle for long time and I submit any transaction I am getting this error.
Please post the answer @tejakiranrayudu, it might help.

**Comment by mcmack25** [comment] 2018-06-09 21:32
@yeganehh I am getting the same issue did you end up getting this resolved?

**Comment by sdg1234** [comment] 2018-07-01 20:06
Hi
i have problem with installing business network and i have encountered following error:
✖ Installing business network. This may take a minute...
Error: Error trying install business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 14 UNAVAILABLE: Connect Failed
Command failed

please help :(

**Comment by apoorvtomar2222** [comment] 2018-07-29 06:49
I faced the same issue. 

What I found out was the issue is with starting of the fabric

     ./startFabric.sh

Make sure this command is successfully executed because it will create an instance in docker and also make sure to check docker running instance by command

    docker ps

(This will show your docker instances)

I am using a mac. and the issue was we need to give access to docker to read our filesystem by navigating into

    Preference -> file ->(Add file where your project is)

and then run the following command again

     ./startFabric.sh

Although I have just started with docker and hyper ledger, these were my finding.

**Comment by prathameshdamji** [comment] 2018-08-08 13:13
Getting a problem while executing the following command...

Command : 
composer network install --card PeerAdmin@hlfv1 --archiveFile block-track@0.0.1.bna 

Problem : 
✖ Installing business network. This may take a minute...
Error: Error trying install business network. Error: No valid responses from any peers.
Response from attempted peer comms was an error: Error: 14 UNAVAILABLE: Connect Failed
Command failed

**Comment by abishekkarthick** [comment] 2018-08-13 13:50
Hi everyone,
I have created a bna file but I am getting error while installing the business network from the tutorial network directory.

![no_valid_responses](https://user-images.githubusercontent.com/36411312/44035763-e0ba4108-9f2d-11e8-885c-17b472fa6a20.png)

Please help me with this error.
Thanks in advance

**Comment by abadraja** [comment] 2018-08-14 12:03
Same error here.

**Comment by ShubhamBhatt18** [comment] 2018-12-04 14:07
factory.newRelationship--where should I include this in
