### ISSUE TITLE
Old resources remain after changing the namespace

### ISSUE THREAD

**Issue by jpayne23** [hyperledger/composer#2249] opened 2017-09-28 13:15 UTC
## Context
If you update the namespace for resources in the staged Composer Playground,the resources will still be shown on the 'Test' page along with resources for the new namespace. You appear to be able to interact with the resources that belong to an outdated namespace but actually can't.

## Expected Behavior
Should not be able to see or have the option to interact with resources that belong to a namespace that doesn't exist anymore.

## Actual Behavior
Resources that belong to a namespace that no longer exists still appear on the 'Test' page. 

## Steps to Reproduce

1. Deploy a business network (I used the basic-sample-network)
2. Change the namespace in a model file
3. Update the business network
4. Go to 'Test' page to see duplicates of resources, one that belongs to the old namespace (that doesn't exist anymore) and one that belongs to the new namespace

## Existing issues
Issue #1792 has a similar result to this issue but different way of getting to it.

## Context
Only affects experience of using playground. Can be confusing to see duplicates of what appears to be the same resource on the left side pane (see screenshot below).

![screen shot 2017-09-28 at 14 06 08](https://user-images.githubusercontent.com/9744866/30968140-3c77e690-a456-11e7-868f-00f15d1b76c1.png)

It appears to the user that you can interact with the resources but interacting with them isn't possible. For example, after clicking 'Create New Participant' for an outdated resource the popup displays as below:

![screen shot 2017-09-28 at 14 07 30](https://user-images.githubusercontent.com/9744866/30968237-89396a3a-a456-11e7-9cd2-a380848e0389.png)

You can click the blue button but it will grey out and never appear to complete what it is trying to do.

## Your Environment
Using the staged Composer Playground on desktop on Firefox version 52.3.0, running on Mac version 10.12.6

**Comment by sstone1** [comment] 2017-09-28 13:24
Duplicate of:
Default registries for types that have been removed are not removed on deployment #1796

**Closed by sstone1** 2017-09-28 13:24 UTC
Labels: duplicate
