### ISSUE TITLE
As a playground user I want to generate a skeleton app without installing commandline

### ISSUE THREAD

**Issue by mqmatt** [hyperledger/composer#1065] opened 2017-05-23 14:57 UTC
## Context
Playground is a great entry point for all Hyperledger Composer users, but the real value of Hyperledger Composer is its ability to easily create end-user applications. The skeleton angular apps work well but today I have to drop to the command line to run the scripts, which makes them difficult to find for a new user.
Incorporating this feature into playground will make the app generation look more integrated with the rest of the toolset.

## Expected Behavior
I should be able to export a sample angular2 or command-line app directly from the playground.

## Actual Behavior
I have to install the command-line tool-set in order to create the skeleton apps.

**Comment by sstone1** [comment] 2017-05-30 19:46
Cancelling as duplicate of https://github.com/hyperledger/composer/issues/925.

**Closed by sstone1** 2017-05-30 19:46 UTC
Labels: duplicate, enhancement, P3
