### ISSUE TITLE
can't create new participant in composer

### ISSUE THREAD

**Issue by praveenala** [hyperledger/composer#4515] opened 2018-11-21 11:50 UTC
Hi,

I could not create new participant in composer, getting below error.

t: Participant 'org.hyperledger.composer.system.NetworkAdmin#admin' does not have 'CREATE' access to resource 'org.acme.airline.aircraft.ACMENetworkAdmin#4414'

Please help me out.

Thanks,
Praveen

**Comment by mahoney1** [comment] 2018-11-26 13:17
@praveenala  lts likely your NetworkAdmin `admin` does not have authority on the `org.acme.airline` business network itself. I suggest to read the docs https://hyperledger.github.io/composer/latest/reference/acl_language or try out the ACL tutorial -> https://hyperledger.github.io/composer/latest/tutorials/acl-trading to see what rules you need to add

**Comment by davidkel** [comment] 2018-12-01 11:35
Closing as this is not a bug in composer but rather than application issue when using ACLs

**Closed by davidkel** 2018-12-01 11:35 UTC
Labels: user error
