### ISSUE TITLE
Documentation on "Installing and developing with Hyperledger Composer" needs correction

### ISSUE THREAD

**Issue by LarissaAuberger** [hyperledger/composer#1613] opened 2017-07-20 02:36 UTC
## Context
The documentation refers to prereqs-ubuntu.sh, but it is not available anymore.
https://hyperledger.github.io/composer/installing/development-tools.html

## Expected Behavior

Please provide instructions on how to install Hyperledger Fabric/Composer prereqs without prereqs-ubuntu.sh. Thanks.

**Comment by davidkel** [comment] 2017-07-20 06:21
This is a duplicate of #1587 which has been fixed and will go out in the next release. The referenced issue also has a workaround you can use for now.

**Comment by davidkel** [comment] 2017-07-20 12:46
This should now be fixed on the website

**Closed by davidkel** 2017-07-20 12:46 UTC

**Comment by LarissaAuberger** [comment] 2017-07-20 12:55
Thanks!
